/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.management.srb.invoice1;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Avishka
 */
public class customer extends javax.swing.JPanel {
Connection con = null;
    PreparedStatement pst1;
    PreparedStatement pst2;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement st=null;
    
    
   
    /**
     * Creates new form customer
     */
    public customer() {
        initComponents();
        dbconnect();
        autoidgen();
        showtable();
        
          c1_AddPane.setVisible(false);
        c1_DeletePane.setVisible(false);
        c1_UpdatePane.setVisible(false);
        c1_ReportPane.setVisible(false);
        c1.setVisible(true);
    }

    
    
     public void dbconnect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/sr_bio_foods","root","");  
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        }
         
    
    public void autoidgen() 
        {
        try {
           
            Statement st = con.createStatement();
            rs = st.executeQuery("select Max(cusid) from customers");
             rs.next();
             rs.getString("Max(cusid)");
             if (rs.getString("Max(cusid)")== null)
             {
                 lblacusid.setText("CU0001");
             }
             else {
                 long id = Long.parseLong(rs.getString("Max(cusid)").substring(2,rs.getString("Max(cusid)").length()));
                 id++;
                 lblacusid.setText("CU" + String.format("%04d",id));
             }
        } catch (SQLException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        
        }
            
        }
    
      public void showtable(){
             try {
            
              Statement st = con.createStatement();
              String sql ="select cusname,cusid,address,business,contactinfo from customers";
               rs = st.executeQuery(sql);
              while (rs.next()){
                  String cusname = rs.getString("cusname");
                  String cusid = rs.getString("cusid");
                   String add = rs.getString("address");
                    String busin = rs.getString("business");
                     String contacde = rs.getString("contactinfo");
                     
                    String custb[] ={cusname,cusid,add,busin,contacde};
                    DefaultTableModel tbmodel = (DefaultTableModel)customershowtable.getModel();
                    tbmodel.addRow(custb);
                     customershowtable.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,14));
                    customershowtable.getTableHeader().setOpaque(false);
                    customershowtable.getTableHeader().setBackground(new Color(32,136,203));
                    customershowtable.getTableHeader().setForeground(new Color(0,0,0));
                    customershowtable.setRowHeight(25);
                    
    
              }
              con.close();
        
        } catch (SQLException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        }
         }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        c1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        addCustomer = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        CustomerReport = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        deleteCustomer = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        updateCustomer = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        c1_AddPane = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        btnGoBack = new javax.swing.JButton();
        lblimagename = new javax.swing.JLabel();
        btnAddCus = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        lblacusid = new javax.swing.JLabel();
        IDtag = new javax.swing.JLabel();
        Nametag = new javax.swing.JLabel();
        txtausname = new javax.swing.JTextField();
        addresstag = new javax.swing.JLabel();
        txtacusaddre = new javax.swing.JTextField();
        txtabusiness = new javax.swing.JTextField();
        businetag = new javax.swing.JLabel();
        infotag = new javax.swing.JLabel();
        txtacontinfo = new javax.swing.JTextField();
        c1_DeletePane = new javax.swing.JPanel();
        header1 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        btnGoBack1 = new javax.swing.JButton();
        lblimagename1 = new javax.swing.JLabel();
        btnDeleteCus = new javax.swing.JButton();
        btnreset1 = new javax.swing.JButton();
        txtcusid1 = new javax.swing.JTextField();
        IDtag2 = new javax.swing.JLabel();
        Nametag2 = new javax.swing.JLabel();
        addresstag2 = new javax.swing.JLabel();
        businetag2 = new javax.swing.JLabel();
        infotag2 = new javax.swing.JLabel();
        txtcontinfo2 = new javax.swing.JTextField();
        txtbusiness2 = new javax.swing.JTextField();
        txtcusaddre2 = new javax.swing.JTextField();
        txtcusname2 = new javax.swing.JTextField();
        c1_UpdatePane = new javax.swing.JPanel();
        header2 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        btnGoBack2 = new javax.swing.JButton();
        lblimagename2 = new javax.swing.JLabel();
        btnUpdateCus = new javax.swing.JButton();
        btnreset2 = new javax.swing.JButton();
        txtcusid = new javax.swing.JTextField();
        txtcusname1 = new javax.swing.JTextField();
        txtcusaddre1 = new javax.swing.JTextField();
        txtbusiness1 = new javax.swing.JTextField();
        txtcontinfo1 = new javax.swing.JTextField();
        infotag1 = new javax.swing.JLabel();
        businetag1 = new javax.swing.JLabel();
        addresstag1 = new javax.swing.JLabel();
        Nametag1 = new javax.swing.JLabel();
        IDtag1 = new javax.swing.JLabel();
        c1_ReportPane = new javax.swing.JPanel();
        header3 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        btnGoBack3 = new javax.swing.JButton();
        lblimagename3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customershowtable = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        c1.setBackground(new java.awt.Color(180, 170, 255));
        c1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 204)));
        c1.setPreferredSize(new java.awt.Dimension(820, 700));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setText("Customer Section");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/icons/information.png"))); // NOI18N
        jLabel15.setToolTipText("");

        addCustomer.setBackground(new java.awt.Color(255, 255, 255));
        addCustomer.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 51, 51)));
        addCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCustomerMouseClicked(evt);
            }
        });
        addCustomer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/icons/c1.png"))); // NOI18N
        addCustomer.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 204, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Add Customer");
        addCustomer.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 130, -1, 20));

        CustomerReport.setBackground(new java.awt.Color(255, 255, 255));
        CustomerReport.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 51, 51)));
        CustomerReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerReportMouseClicked(evt);
            }
        });
        CustomerReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/icons/c4.png"))); // NOI18N
        CustomerReport.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Customer Report");
        CustomerReport.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 20));

        deleteCustomer.setBackground(new java.awt.Color(255, 255, 255));
        deleteCustomer.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 51, 51)));
        deleteCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteCustomerMouseClicked(evt);
            }
        });
        deleteCustomer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/icons/c2.png"))); // NOI18N
        deleteCustomer.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Delete Customer");
        deleteCustomer.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 130, -1, 20));

        updateCustomer.setBackground(new java.awt.Color(255, 255, 255));
        updateCustomer.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 51, 51)));
        updateCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateCustomerMouseClicked(evt);
            }
        });
        updateCustomer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/icons/c3.png"))); // NOI18N
        updateCustomer.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 0, 204));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Update Customer");
        updateCustomer.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 130, -1, 20));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Welcome to Invoice System");

        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 0, 1, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout c1Layout = new javax.swing.GroupLayout(c1);
        c1.setLayout(c1Layout);
        c1Layout.setHorizontalGroup(
            c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(c1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(c1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(c1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(addCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(c1Layout.createSequentialGroup()
                        .addComponent(CustomerReport, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(c1Layout.createSequentialGroup()
                        .addComponent(deleteCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(updateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        c1Layout.setVerticalGroup(
            c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(c1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(25, 25, 25)
                .addGroup(c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(deleteCustomer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addComponent(addCustomer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(updateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(CustomerReport, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        c1_AddPane.setBackground(new java.awt.Color(200, 210, 255));
        c1_AddPane.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 204, 204)));
        c1_AddPane.setToolTipText("");
        c1_AddPane.setPreferredSize(new java.awt.Dimension(810, 712));

        header.setBackground(new java.awt.Color(0, 0, 104));
        header.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Add Customer :");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addContainerGap(694, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnGoBack.setBackground(new java.awt.Color(255, 0, 51));
        btnGoBack.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnGoBack.setForeground(new java.awt.Color(255, 255, 255));
        btnGoBack.setText("Go Back");
        btnGoBack.setBorderPainted(false);
        btnGoBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        lblimagename.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnAddCus.setBackground(new java.awt.Color(0, 0, 102));
        btnAddCus.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnAddCus.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCus.setText("Add Customer");
        btnAddCus.setBorderPainted(false);
        btnAddCus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCusActionPerformed(evt);
            }
        });

        btnreset.setBackground(new java.awt.Color(255, 153, 0));
        btnreset.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnreset.setForeground(new java.awt.Color(255, 255, 255));
        btnreset.setText("Reset");
        btnreset.setBorderPainted(false);
        btnreset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        lblacusid.setBackground(new java.awt.Color(255, 255, 255));
        lblacusid.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        lblacusid.setForeground(new java.awt.Color(51, 51, 51));
        lblacusid.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));

        IDtag.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        IDtag.setForeground(new java.awt.Color(51, 51, 51));
        IDtag.setText("Customer ID:");

        Nametag.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Nametag.setForeground(new java.awt.Color(51, 51, 51));
        Nametag.setText("Address :");

        txtausname.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtausname.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtausname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtausnameKeyPressed(evt);
            }
        });

        addresstag.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        addresstag.setForeground(new java.awt.Color(51, 51, 51));
        addresstag.setText("Customer Name:");

        txtacusaddre.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtacusaddre.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtacusaddre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtacusaddreKeyPressed(evt);
            }
        });

        txtabusiness.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtabusiness.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtabusiness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtabusinessActionPerformed(evt);
            }
        });
        txtabusiness.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtabusinessKeyPressed(evt);
            }
        });

        businetag.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        businetag.setForeground(new java.awt.Color(51, 51, 51));
        businetag.setText("Busniess :");

        infotag.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        infotag.setForeground(new java.awt.Color(51, 51, 51));
        infotag.setText("Contact Information :");

        txtacontinfo.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtacontinfo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtacontinfo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtacontinfoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout c1_AddPaneLayout = new javax.swing.GroupLayout(c1_AddPane);
        c1_AddPane.setLayout(c1_AddPaneLayout);
        c1_AddPaneLayout.setHorizontalGroup(
            c1_AddPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(c1_AddPaneLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(btnAddCus, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(c1_AddPaneLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(c1_AddPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nametag, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(businetag)
                    .addComponent(infotag)
                    .addGroup(c1_AddPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(addresstag, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IDtag, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                .addGap(35, 35, 35)
                .addGroup(c1_AddPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(c1_AddPaneLayout.createSequentialGroup()
                        .addComponent(txtacusaddre, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblimagename, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtausname, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblacusid, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtabusiness, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtacontinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        c1_AddPaneLayout.setVerticalGroup(
            c1_AddPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(c1_AddPaneLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(c1_AddPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblacusid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, c1_AddPaneLayout.createSequentialGroup()
                        .addComponent(IDtag, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGap(30, 30, 30)
                .addGroup(c1_AddPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtausname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addresstag, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(c1_AddPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(c1_AddPaneLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblimagename, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(c1_AddPaneLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(c1_AddPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtacusaddre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nametag, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(c1_AddPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtabusiness, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(businetag))
                .addGap(30, 30, 30)
                .addGroup(c1_AddPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtacontinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infotag))
                .addGap(210, 210, 210)
                .addGroup(c1_AddPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGoBack, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btnreset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddCus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        add(c1_AddPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 700));

        c1_DeletePane.setBackground(new java.awt.Color(200, 210, 255));
        c1_DeletePane.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 204, 204)));
        c1_DeletePane.setToolTipText("");
        c1_DeletePane.setPreferredSize(new java.awt.Dimension(810, 712));

        header1.setBackground(new java.awt.Color(0, 0, 104));
        header1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Delete Customer :");

        javax.swing.GroupLayout header1Layout = new javax.swing.GroupLayout(header1);
        header1.setLayout(header1Layout);
        header1Layout.setHorizontalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addContainerGap(695, Short.MAX_VALUE))
        );
        header1Layout.setVerticalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnGoBack1.setBackground(new java.awt.Color(255, 0, 51));
        btnGoBack1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnGoBack1.setForeground(new java.awt.Color(255, 255, 255));
        btnGoBack1.setText("Go Back");
        btnGoBack1.setBorderPainted(false);
        btnGoBack1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBack1ActionPerformed(evt);
            }
        });

        lblimagename1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnDeleteCus.setBackground(new java.awt.Color(0, 0, 102));
        btnDeleteCus.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnDeleteCus.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteCus.setText("Delete Customer");
        btnDeleteCus.setBorderPainted(false);
        btnDeleteCus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCusActionPerformed(evt);
            }
        });

        btnreset1.setBackground(new java.awt.Color(255, 153, 0));
        btnreset1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnreset1.setForeground(new java.awt.Color(255, 255, 255));
        btnreset1.setText("Reset");
        btnreset1.setBorderPainted(false);
        btnreset1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreset1ActionPerformed(evt);
            }
        });

        txtcusid1.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtcusid1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtcusid1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcusid1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcusid1KeyReleased(evt);
            }
        });

        IDtag2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        IDtag2.setForeground(new java.awt.Color(51, 51, 51));
        IDtag2.setText("Customer ID:");

        Nametag2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Nametag2.setForeground(new java.awt.Color(51, 51, 51));
        Nametag2.setText("Customer Name :");

        addresstag2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        addresstag2.setForeground(new java.awt.Color(51, 51, 51));
        addresstag2.setText("Address :");

        businetag2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        businetag2.setForeground(new java.awt.Color(51, 51, 51));
        businetag2.setText("Busniess :");

        infotag2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        infotag2.setForeground(new java.awt.Color(51, 51, 51));
        infotag2.setText("Contact Information :");

        txtcontinfo2.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtcontinfo2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));

        txtbusiness2.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtbusiness2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));

        txtcusaddre2.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtcusaddre2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));

        txtcusname2.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtcusname2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));

        javax.swing.GroupLayout c1_DeletePaneLayout = new javax.swing.GroupLayout(c1_DeletePane);
        c1_DeletePane.setLayout(c1_DeletePaneLayout);
        c1_DeletePaneLayout.setHorizontalGroup(
            c1_DeletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(c1_DeletePaneLayout.createSequentialGroup()
                .addGroup(c1_DeletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(c1_DeletePaneLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnGoBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(btnreset1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(btnDeleteCus, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, c1_DeletePaneLayout.createSequentialGroup()
                .addGroup(c1_DeletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(c1_DeletePaneLayout.createSequentialGroup()
                        .addGap(480, 480, 480)
                        .addComponent(lblimagename1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(c1_DeletePaneLayout.createSequentialGroup()
                        .addComponent(infotag2)
                        .addGap(24, 24, 24)
                        .addComponent(txtcontinfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(c1_DeletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, c1_DeletePaneLayout.createSequentialGroup()
                            .addComponent(addresstag2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtcusaddre2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, c1_DeletePaneLayout.createSequentialGroup()
                            .addComponent(businetag2)
                            .addGap(99, 99, 99)
                            .addComponent(txtbusiness2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(c1_DeletePaneLayout.createSequentialGroup()
                            .addGroup(c1_DeletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(IDtag2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Nametag2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(c1_DeletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtcusname2)
                                .addComponent(txtcusid1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        c1_DeletePaneLayout.setVerticalGroup(
            c1_DeletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(c1_DeletePaneLayout.createSequentialGroup()
                .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(c1_DeletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcusid1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDtag2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(c1_DeletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcusname2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nametag2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(c1_DeletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcusaddre2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addresstag2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(c1_DeletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbusiness2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(businetag2))
                .addGap(30, 30, 30)
                .addGroup(c1_DeletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcontinfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infotag2))
                .addGap(30, 30, 30)
                .addComponent(lblimagename1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168)
                .addGroup(c1_DeletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDeleteCus, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btnreset1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGoBack1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        add(c1_DeletePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 700));

        c1_UpdatePane.setBackground(new java.awt.Color(200, 210, 255));
        c1_UpdatePane.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 204, 204)));
        c1_UpdatePane.setToolTipText("");
        c1_UpdatePane.setPreferredSize(new java.awt.Dimension(810, 712));

        header2.setBackground(new java.awt.Color(0, 0, 104));
        header2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Update Customer :");

        javax.swing.GroupLayout header2Layout = new javax.swing.GroupLayout(header2);
        header2.setLayout(header2Layout);
        header2Layout.setHorizontalGroup(
            header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addContainerGap(689, Short.MAX_VALUE))
        );
        header2Layout.setVerticalGroup(
            header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnGoBack2.setBackground(new java.awt.Color(255, 0, 51));
        btnGoBack2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnGoBack2.setForeground(new java.awt.Color(255, 255, 255));
        btnGoBack2.setText("Go Back");
        btnGoBack2.setBorderPainted(false);
        btnGoBack2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBack2ActionPerformed(evt);
            }
        });

        lblimagename2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnUpdateCus.setBackground(new java.awt.Color(0, 0, 102));
        btnUpdateCus.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnUpdateCus.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateCus.setText("Update Customer");
        btnUpdateCus.setBorderPainted(false);
        btnUpdateCus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCusActionPerformed(evt);
            }
        });

        btnreset2.setBackground(new java.awt.Color(255, 153, 0));
        btnreset2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnreset2.setForeground(new java.awt.Color(255, 255, 255));
        btnreset2.setText("Reset");
        btnreset2.setBorderPainted(false);
        btnreset2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreset2ActionPerformed(evt);
            }
        });

        txtcusid.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtcusid.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtcusid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcusidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcusidKeyReleased(evt);
            }
        });

        txtcusname1.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtcusname1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtcusname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcusname1ActionPerformed(evt);
            }
        });
        txtcusname1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcusname1KeyPressed(evt);
            }
        });

        txtcusaddre1.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtcusaddre1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtcusaddre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcusaddre1KeyPressed(evt);
            }
        });

        txtbusiness1.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtbusiness1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtbusiness1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbusiness1KeyPressed(evt);
            }
        });

        txtcontinfo1.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtcontinfo1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtcontinfo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcontinfo1KeyPressed(evt);
            }
        });

        infotag1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        infotag1.setForeground(new java.awt.Color(51, 51, 51));
        infotag1.setText("Contact Information  :");

        businetag1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        businetag1.setForeground(new java.awt.Color(51, 51, 51));
        businetag1.setText("Business :");

        addresstag1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        addresstag1.setForeground(new java.awt.Color(51, 51, 51));
        addresstag1.setText("Address :");

        Nametag1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Nametag1.setForeground(new java.awt.Color(51, 51, 51));
        Nametag1.setText("Customer Name :");

        IDtag1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        IDtag1.setForeground(new java.awt.Color(51, 51, 51));
        IDtag1.setText("Customer ID:");

        javax.swing.GroupLayout c1_UpdatePaneLayout = new javax.swing.GroupLayout(c1_UpdatePane);
        c1_UpdatePane.setLayout(c1_UpdatePaneLayout);
        c1_UpdatePaneLayout.setHorizontalGroup(
            c1_UpdatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(c1_UpdatePaneLayout.createSequentialGroup()
                .addGap(551, 551, 551)
                .addComponent(lblimagename2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(c1_UpdatePaneLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnGoBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(btnreset2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(btnUpdateCus, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(c1_UpdatePaneLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(c1_UpdatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(c1_UpdatePaneLayout.createSequentialGroup()
                        .addComponent(infotag1)
                        .addGap(29, 29, 29)
                        .addComponent(txtcontinfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(c1_UpdatePaneLayout.createSequentialGroup()
                        .addGroup(c1_UpdatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(businetag1)
                            .addComponent(addresstag1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nametag1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDtag1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(c1_UpdatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcusid, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcusname1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcusaddre1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbusiness1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        c1_UpdatePaneLayout.setVerticalGroup(
            c1_UpdatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(c1_UpdatePaneLayout.createSequentialGroup()
                .addComponent(header2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addGroup(c1_UpdatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcusid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDtag1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(c1_UpdatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcusname1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nametag1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(c1_UpdatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcusaddre1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addresstag1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(c1_UpdatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbusiness1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(businetag1))
                .addGap(30, 30, 30)
                .addGroup(c1_UpdatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcontinfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infotag1))
                .addGap(10, 10, 10)
                .addComponent(lblimagename2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addGroup(c1_UpdatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnreset2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btnGoBack2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateCus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        add(c1_UpdatePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 700));

        c1_ReportPane.setBackground(new java.awt.Color(200, 210, 255));
        c1_ReportPane.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 204, 204)));
        c1_ReportPane.setToolTipText("");
        c1_ReportPane.setPreferredSize(new java.awt.Dimension(810, 712));
        c1_ReportPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header3.setBackground(new java.awt.Color(0, 0, 104));
        header3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Report :");

        javax.swing.GroupLayout header3Layout = new javax.swing.GroupLayout(header3);
        header3.setLayout(header3Layout);
        header3Layout.setHorizontalGroup(
            header3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel41)
                .addContainerGap(771, Short.MAX_VALUE))
        );
        header3Layout.setVerticalGroup(
            header3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        c1_ReportPane.add(header3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, -1));

        btnGoBack3.setBackground(new java.awt.Color(255, 0, 51));
        btnGoBack3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnGoBack3.setForeground(new java.awt.Color(255, 255, 255));
        btnGoBack3.setText("Go Back");
        btnGoBack3.setBorderPainted(false);
        btnGoBack3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBack3ActionPerformed(evt);
            }
        });
        c1_ReportPane.add(btnGoBack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, 170, 30));

        lblimagename3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c1_ReportPane.add(lblimagename3, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 470, 250, 20));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        customershowtable.setBackground(new java.awt.Color(122, 204, 255));
        customershowtable.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 204, 204)));
        customershowtable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        customershowtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CUSTOMER NAME", "CUSTOMER ID", "ADDRESS", "BUSINESS", "CONTACT DETAILS"
            }
        ));
        customershowtable.setFocusable(false);
        customershowtable.setSelectionBackground(new java.awt.Color(102, 40, 204));
        customershowtable.setSelectionForeground(new java.awt.Color(204, 255, 255));
        customershowtable.setShowVerticalLines(false);
        jScrollPane1.setViewportView(customershowtable);

        c1_ReportPane.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 780, 380));

        add(c1_ReportPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void addCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCustomerMouseClicked
        // TODO add your handling code here:
        c1_AddPane.setVisible(true);
        c1_DeletePane.setVisible(false);
        c1_UpdatePane.setVisible(false);
        c1_ReportPane.setVisible(false);
       

        c1.setVisible(false);

    }//GEN-LAST:event_addCustomerMouseClicked

    private void CustomerReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerReportMouseClicked
         c1_AddPane.setVisible(false);
        c1_DeletePane.setVisible(false);
        c1_UpdatePane.setVisible(false);
        c1_ReportPane.setVisible(true);
       

        c1.setVisible(false);
    }//GEN-LAST:event_CustomerReportMouseClicked

    private void deleteCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteCustomerMouseClicked
        // TODO add your handling code here:
         c1_AddPane.setVisible(false);
        c1_DeletePane.setVisible(true);
        c1_UpdatePane.setVisible(false);
        c1_ReportPane.setVisible(false);
       

        c1.setVisible(false);

    }//GEN-LAST:event_deleteCustomerMouseClicked

    private void updateCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateCustomerMouseClicked
        // TODO add your handling code here:
       c1_AddPane.setVisible(false);
        c1_DeletePane.setVisible(false);
        c1_UpdatePane.setVisible(true);
        c1_ReportPane.setVisible(false);
       

        c1.setVisible(false);
    }//GEN-LAST:event_updateCustomerMouseClicked

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        // TODO add your handling code here:
         c1_AddPane.setVisible(false);
        c1_DeletePane.setVisible(false);
        c1_UpdatePane.setVisible(false);
        c1_ReportPane.setVisible(false);
       

        c1.setVisible(true);

    }//GEN-LAST:event_btnGoBackActionPerformed

    private void btnAddCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCusActionPerformed
 if(txtausname.getText().isEmpty()){
            txtausname.setBackground(new Color(255,0,51));
            JOptionPane.showMessageDialog(this,"Missing Information");
        }
        else if(txtacusaddre.getText().isEmpty()){
            txtacusaddre.setBackground(new Color(255,0,51));
            JOptionPane.showMessageDialog(this,"Missing Information");
        }
        else if(txtabusiness.getText().isEmpty()){
            txtabusiness.setBackground(new Color(255,0,51));
            JOptionPane.showMessageDialog(this,"Missing Information");}
        else if(txtacontinfo.getText().isEmpty()){
            txtacontinfo.setBackground(new Color(255,0,51));
            JOptionPane.showMessageDialog(this,"Missing Information");}
       
         else
        {
            int opt =JOptionPane.showConfirmDialog(null,"Are you sure to add this record!!","Add Record",JOptionPane.YES_NO_OPTION);
            if (opt==0)

            {
            
         
                try {
                    String query = "insert into customers (cusname,cusid,address,business,contactinfo)values (?,?,?,?,?)";
                    
                    con = DriverManager.getConnection("jdbc:mysql://localhost/sr_bio_foods", "root", "");
                    pst=con.prepareStatement(query);

                  
                    pst.setString(1,txtausname.getText());
                    pst.setString(2,lblacusid.getText());
                    pst.setString(3,txtacusaddre.getText());
                    pst.setString(4,txtabusiness.getText());
                    pst.setString(5,txtacontinfo.getText());
                    
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Inserted Successfully ");
                    txtausname.setText("");
                    txtacusaddre.setText("");
                    txtabusiness.setText("");
                    txtacontinfo.setText("");
                   
                     autoidgen();
                } catch(Exception ex){
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                    
                }
            } 
        }
        
 showtable();
    }//GEN-LAST:event_btnAddCusActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
       txtausname.setText("");
              
                txtacusaddre.setText("");
                txtabusiness.setText("");
                txtacontinfo.setText("");
               

      
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnGoBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBack1ActionPerformed
         c1_AddPane.setVisible(false);
        c1_DeletePane.setVisible(false);
        c1_UpdatePane.setVisible(false);
        c1_ReportPane.setVisible(false);
       

        c1.setVisible(true);
    }//GEN-LAST:event_btnGoBack1ActionPerformed

    private void btnDeleteCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCusActionPerformed
if(txtcusid1.getText().isEmpty())
{
      txtcusid1.setBackground(new Color(255,0,51));
            JOptionPane.showMessageDialog(this,"Missing Information");
}
else
{
        
        int opt =JOptionPane.showConfirmDialog(null,"Are you sure to Delete this record!!","Delete Record",JOptionPane.YES_NO_OPTION);
            if (opt==0)

            {
        
        try {
            
            
           pst = con.prepareStatement("delete from customers where cusid = ?");
           pst.setString(1,txtcusid1.getText());
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null,"DELETE SUCCESSFULLY");
            txtcusname2.setText("");
               txtcusid1.setText("");
               txtcusaddre2.setText("");
               txtbusiness2.setText("");
               txtcontinfo2.setText("");
           
        
        } catch (SQLException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        }
            }
}
 showtable();
    }//GEN-LAST:event_btnDeleteCusActionPerformed

    private void btnreset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreset1ActionPerformed
        txtcusname2.setText("");
               txtcusid1.setText("");
               txtcusaddre2.setText("");
               txtbusiness2.setText("");
               txtcontinfo2.setText("");
    }//GEN-LAST:event_btnreset1ActionPerformed

    private void btnGoBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBack2ActionPerformed
          c1_AddPane.setVisible(false);
        c1_DeletePane.setVisible(false);
        c1_UpdatePane.setVisible(false);
        c1_ReportPane.setVisible(false);
       

        c1.setVisible(true);
    }//GEN-LAST:event_btnGoBack2ActionPerformed

    private void btnUpdateCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCusActionPerformed
        if(txtcusname1.getText().isEmpty()){
          txtcusname1.setBackground(new Color(255,0,51));
            JOptionPane.showMessageDialog(this,"Missing Information");
      }
      else if(txtcusid.getText().isEmpty()){
          txtcusid.setBackground(new Color(255,0,51));
            JOptionPane.showMessageDialog(this,"Missing Information");
      }
      else if(txtcusaddre1.getText().isEmpty()){
          txtcusaddre1.setBackground(new Color(255,0,51));
            JOptionPane.showMessageDialog(this,"Missing Information");
      }
      else if(txtbusiness1.getText().isEmpty()){
          txtbusiness1.setBackground(new Color(255,0,51));
            JOptionPane.showMessageDialog(this,"Missing Information");
      }
      else if(txtcontinfo1.getText().isEmpty()){
          txtcontinfo1.setBackground(new Color(255,0,51));
            JOptionPane.showMessageDialog(this,"Missing Information");
      }
      else {
          
            int opt =JOptionPane.showConfirmDialog(null,"Are you sure to update this record!!","update Record",JOptionPane.YES_NO_OPTION);
            if (opt==0)

            {
            
        try {
            
             String le = "update customers set cusname=?,address=?,business=?,contactinfo=? where cusid=?";
           con = DriverManager.getConnection("jdbc:mysql://localhost/sr_bio_foods", "root", "");
            pst=con.prepareStatement(le);
            pst.setString(1,  txtcusname1.getText());
            pst.setString(2, txtcusaddre1.getText());
            pst.setString(3, txtbusiness1.getText());
            pst.setString(4, txtcontinfo1.getText());
           
            pst.setString(5, txtcusid.getText());
           
           pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"UPDATE SUCCESSFULLY");
               txtcusname1.setText("");
               txtcusaddre1.setText("");
               txtbusiness1.setText("");
               txtcontinfo1.setText("");
           
        }  catch(Exception ex){
                    JOptionPane.showMessageDialog(this, ex.getMessage());

                }
      }
          }
         showtable();
    }//GEN-LAST:event_btnUpdateCusActionPerformed

    private void btnreset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreset2ActionPerformed
         txtcusname1.setText("");
               txtcusid.setText("");
               txtcusaddre1.setText("");
               txtbusiness1.setText("");
               txtcontinfo1.setText("");
    }//GEN-LAST:event_btnreset2ActionPerformed

    private void btnGoBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBack3ActionPerformed
        c1_AddPane.setVisible(false);
        c1_DeletePane.setVisible(false);
        c1_UpdatePane.setVisible(false);
        c1_ReportPane.setVisible(false);
       

        c1.setVisible(true);
    }//GEN-LAST:event_btnGoBack3ActionPerformed

    private void txtausnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtausnameKeyPressed
       txtausname.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_txtausnameKeyPressed

    private void txtacusaddreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtacusaddreKeyPressed
       txtacusaddre.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_txtacusaddreKeyPressed

    private void txtabusinessKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtabusinessKeyPressed
       txtabusiness.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_txtabusinessKeyPressed

    private void txtacontinfoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtacontinfoKeyPressed
        txtacontinfo.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_txtacontinfoKeyPressed

    private void txtcusidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcusidKeyPressed
     txtcusid.setBackground(new Color(255,255,255));
        
       
    }//GEN-LAST:event_txtcusidKeyPressed

    private void txtcusid1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcusid1KeyPressed
      
    }//GEN-LAST:event_txtcusid1KeyPressed

    private void txtcusname1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcusname1KeyPressed
     txtcusname1.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_txtcusname1KeyPressed

    private void txtcusaddre1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcusaddre1KeyPressed
        txtcusaddre1.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_txtcusaddre1KeyPressed

    private void txtbusiness1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusiness1KeyPressed
        txtbusiness1.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_txtbusiness1KeyPressed

    private void txtcontinfo1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontinfo1KeyPressed
       txtcontinfo1.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_txtcontinfo1KeyPressed

    private void txtcusidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcusidKeyReleased
         try {

             String sql =("select cusname,address,business,contactinfo from customers where cusid = ?");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/sr_bio_foods", "root", "");
            pst=(PreparedStatement) con.prepareStatement(sql);

            pst.setString(1, txtcusid.getText());
            rs= (ResultSet) pst.executeQuery();
           
            if (rs.next()){
               
                String custname =rs.getString("cusname");
                txtcusname1.setText(custname);
                String addr =rs.getString("address");
                txtcusaddre1.setText(addr);
                String busin =rs.getString("business");
                txtbusiness1.setText(busin);
                String coin =rs.getString("contactinfo");
                txtcontinfo1.setText(coin);
            }
           
        }  catch(Exception ex){
                    JOptionPane.showMessageDialog(this, ex.getMessage());

                }
    }//GEN-LAST:event_txtcusidKeyReleased

    private void txtcusid1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcusid1KeyReleased
      try {

             String sql =("select cusname,address,business,contactinfo from customers where cusid = ?");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/sr_bio_foods", "root", "");
            pst=(PreparedStatement) con.prepareStatement(sql);

            pst.setString(1, txtcusid1.getText());
            rs= (ResultSet) pst.executeQuery();
           
            if (rs.next()){
               
                String custname =rs.getString("cusname");
                txtcusname2.setText(custname);
                String addr =rs.getString("address");
                txtcusaddre2.setText(addr);
                String busin =rs.getString("business");
                txtbusiness2.setText(busin);
                String coin =rs.getString("contactinfo");
                txtcontinfo2.setText(coin);
            }
           
        }  catch(Exception ex){
                    JOptionPane.showMessageDialog(this, ex.getMessage());

                }
    }//GEN-LAST:event_txtcusid1KeyReleased

    private void txtabusinessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtabusinessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtabusinessActionPerformed

    private void txtcusname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcusname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcusname1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CustomerReport;
    private javax.swing.JLabel IDtag;
    private javax.swing.JLabel IDtag1;
    private javax.swing.JLabel IDtag2;
    private javax.swing.JLabel Nametag;
    private javax.swing.JLabel Nametag1;
    private javax.swing.JLabel Nametag2;
    private javax.swing.JPanel addCustomer;
    private javax.swing.JLabel addresstag;
    private javax.swing.JLabel addresstag1;
    private javax.swing.JLabel addresstag2;
    private javax.swing.JButton btnAddCus;
    private javax.swing.JButton btnDeleteCus;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnGoBack1;
    private javax.swing.JButton btnGoBack2;
    private javax.swing.JButton btnGoBack3;
    private javax.swing.JButton btnUpdateCus;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnreset1;
    private javax.swing.JButton btnreset2;
    private javax.swing.JLabel businetag;
    private javax.swing.JLabel businetag1;
    private javax.swing.JLabel businetag2;
    private javax.swing.JPanel c1;
    private javax.swing.JPanel c1_AddPane;
    private javax.swing.JPanel c1_DeletePane;
    private javax.swing.JPanel c1_ReportPane;
    private javax.swing.JPanel c1_UpdatePane;
    private javax.swing.JTable customershowtable;
    private javax.swing.JPanel deleteCustomer;
    private javax.swing.JPanel header;
    private javax.swing.JPanel header1;
    private javax.swing.JPanel header2;
    private javax.swing.JPanel header3;
    private javax.swing.JLabel infotag;
    private javax.swing.JLabel infotag1;
    private javax.swing.JLabel infotag2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblacusid;
    private javax.swing.JLabel lblimagename;
    private javax.swing.JLabel lblimagename1;
    private javax.swing.JLabel lblimagename2;
    private javax.swing.JLabel lblimagename3;
    private javax.swing.JTextField txtabusiness;
    private javax.swing.JTextField txtacontinfo;
    private javax.swing.JTextField txtacusaddre;
    private javax.swing.JTextField txtausname;
    private javax.swing.JTextField txtbusiness1;
    private javax.swing.JTextField txtbusiness2;
    private javax.swing.JTextField txtcontinfo1;
    private javax.swing.JTextField txtcontinfo2;
    private javax.swing.JTextField txtcusaddre1;
    private javax.swing.JTextField txtcusaddre2;
    private javax.swing.JTextField txtcusid;
    private javax.swing.JTextField txtcusid1;
    private javax.swing.JTextField txtcusname1;
    private javax.swing.JTextField txtcusname2;
    private javax.swing.JPanel updateCustomer;
    // End of variables declaration//GEN-END:variables
}
