/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.management.srb.invoice1;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Pageable;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Janith
 */
public class print_sales_order extends javax.swing.JFrame {

    /**
     * Creates new form print_sales_order
     */
    public print_sales_order() {
        initComponents();
    }
    
     public void changecolor(JPanel hover,Color rand){
        hover.setBackground(rand);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        print_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        printordertype = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblorderid = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        lblordtyp = new javax.swing.JLabel();
        lblcusid = new javax.swing.JLabel();
        lblcusname = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productable = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbltotamu = new javax.swing.JLabel();
        lblpay = new javax.swing.JLabel();
        lblbala = new javax.swing.JLabel();
        lblordstu = new javax.swing.JLabel();
        printpanel = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        print_subpanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainpanel.setBackground(new java.awt.Color(0, 204, 255));
        mainpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        print_panel.setBackground(new java.awt.Color(255, 255, 255));
        print_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/icons/SR copy.png"))); // NOI18N
        print_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 110, 110));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SR Bio Food Products (Pvt) Ltd");
        print_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 390, 40));

        printordertype.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        printordertype.setForeground(new java.awt.Color(0, 0, 153));
        printordertype.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        printordertype.setText("Sales order Recipt");
        print_panel.add(printordertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 300, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Order ID:");
        print_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Date :");
        print_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Order Type :");
        print_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Customer ID :");
        print_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 110, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Customer Name :");
        print_panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 140, 30));

        lblorderid.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblorderid.setForeground(new java.awt.Color(0, 0, 102));
        lblorderid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        print_panel.add(lblorderid, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 140, 20));

        lbldate.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbldate.setForeground(new java.awt.Color(0, 0, 102));
        lbldate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        print_panel.add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 140, 20));

        lblordtyp.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblordtyp.setForeground(new java.awt.Color(0, 0, 102));
        print_panel.add(lblordtyp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 184, 190, 30));

        lblcusid.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblcusid.setForeground(new java.awt.Color(0, 0, 102));
        print_panel.add(lblcusid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 214, 190, 30));

        lblcusname.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblcusname.setForeground(new java.awt.Color(0, 0, 102));
        print_panel.add(lblcusname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 260, 30));

        productable.setBackground(new java.awt.Color(122, 204, 255));
        productable.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 204, 204)));
        productable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        productable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT", "PRODUCT ID", "GRADE", "QTY", "UNIT PRICE", "AMOUNT"
            }
        ));
        productable.setFocusable(false);
        productable.setSelectionBackground(new java.awt.Color(102, 40, 204));
        productable.setShowVerticalLines(false);
        jScrollPane1.setViewportView(productable);

        print_panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 580, 220));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setText("Total Amount :");
        print_panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 550, 120, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setText("Pay :");
        print_panel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 590, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel15.setText("Balance :");
        print_panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 630, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setText("Order Status :");
        print_panel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, -1, -1));

        lbltotamu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbltotamu.setForeground(new java.awt.Color(0, 0, 102));
        print_panel.add(lbltotamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 140, 30));

        lblpay.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblpay.setForeground(new java.awt.Color(0, 0, 102));
        print_panel.add(lblpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, 140, 30));

        lblbala.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblbala.setForeground(new java.awt.Color(0, 0, 102));
        print_panel.add(lblbala, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 624, 140, 30));

        lblordstu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblordstu.setForeground(new java.awt.Color(0, 0, 102));
        print_panel.add(lblordstu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 680, 160, 30));

        mainpanel.add(print_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 600, 730));

        printpanel.setBackground(new java.awt.Color(0, 0, 102));
        printpanel.setForeground(new java.awt.Color(255, 255, 255));
        printpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                printpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                printpanelMouseExited(evt);
            }
        });
        printpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Print");
        printpanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 70, 30));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/icons/print icon.png"))); // NOI18N
        printpanel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, 50));

        print_subpanel.setBackground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout print_subpanelLayout = new javax.swing.GroupLayout(print_subpanel);
        print_subpanel.setLayout(print_subpanelLayout);
        print_subpanelLayout.setHorizontalGroup(
            print_subpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        print_subpanelLayout.setVerticalGroup(
            print_subpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        printpanel.add(print_subpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 10));

        mainpanel.add(printpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 780, 200, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/icons/Button-Close-icon (1).png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        mainpanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void printpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printpanelMouseClicked
     printrcp(print_panel);
      
    }//GEN-LAST:event_printpanelMouseClicked

    private void printpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printpanelMouseEntered
        changecolor(print_subpanel,new Color (204,0,0));
    }//GEN-LAST:event_printpanelMouseEntered

    private void printpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printpanelMouseExited
        changecolor(print_subpanel,new Color (0,0,102));
    }//GEN-LAST:event_printpanelMouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        setVisible(false);
    }//GEN-LAST:event_jLabel8MouseClicked

    
    private void printrcp(JPanel panel){
        PrinterJob prtjob = PrinterJob.getPrinterJob();
        prtjob.setJobName("print record");
        prtjob.setPrintable(new Printable() {
           @Override
           public int print (Graphics graphics, PageFormat pageformat,int PageIndex) {
               if (PageIndex > 0){
                   return Printable.NO_SUCH_PAGE;
               }
               Graphics2D graphics2D = (Graphics2D)graphics;
               graphics2D.translate(pageformat.getImageableX(),pageformat.getImageableY());
               graphics2D.scale(0.5,0.5);
               panel.paint(graphics2D);
               return Printable.PAGE_EXISTS;
           }
            });
        boolean returningResult = prtjob.printDialog();
        if(returningResult){
            try{
                prtjob.print();
            }catch (PrinterException pe){
                JOptionPane.showMessageDialog(this,"print Error"+pe.getMessage());
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(print_sales_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(print_sales_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(print_sales_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(print_sales_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new print_sales_order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblbala;
    public static javax.swing.JLabel lblcusid;
    public static javax.swing.JLabel lblcusname;
    public static javax.swing.JLabel lbldate;
    public static javax.swing.JLabel lblorderid;
    public static javax.swing.JLabel lblordstu;
    public static javax.swing.JLabel lblordtyp;
    public static javax.swing.JLabel lblpay;
    public static javax.swing.JLabel lbltotamu;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel print_panel;
    private javax.swing.JPanel print_subpanel;
    private javax.swing.JLabel printordertype;
    private javax.swing.JPanel printpanel;
    public static javax.swing.JTable productable;
    // End of variables declaration//GEN-END:variables
}
