/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.management.srb.invoice1;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Avishka
 */
public class supplier extends javax.swing.JPanel {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    /**
     * Creates new form supplier
     */
    public supplier() {
        initComponents();
        dbconnect();
        autoidgen();
        showtable();
        sup1_AddPane.setVisible(false);
        sup1_DeletePane.setVisible(false);
        sup1_UpdatePane.setVisible(false);
        sup1_ReportPane.setVisible(false);

        sup1.setVisible(true);

    }

    public void dbconnect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/sr_bio_foods", "root", "");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(supplier.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(supplier.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void autoidgen() {
        try {

            Statement st = con.createStatement();
            rs = st.executeQuery("select Max(supplierid) from suppliers");
            rs.next();
            rs.getString("Max(supplierid)");
            if (rs.getString("Max(supplierid)") == null) {
                txtsuppid.setText("SUP0001");
            } else {
                long id = Long.parseLong(rs.getString("Max(supplierid)").substring(4, rs.getString("Max(supplierid)").length()));
                id++;
                txtsuppid.setText("SUP" + String.format("%04d", id));
            }
        } catch (SQLException ex) {
            Logger.getLogger(supplier.class.getName()).log(Level.SEVERE, null, ex);

        }

    }

    public void showtable() {
        try {

            Statement st = con.createStatement();
            String sql = "select * from suppliers";
            rs = st.executeQuery(sql);
            while (rs.next()) {
                String supname = rs.getString("supplier_name");
                String supid = rs.getString("supplierid");
                String add = rs.getString("address");
                String product = rs.getString("products");
                String contacde = rs.getString("contactinfo");

                String custb[] = {supname, supid, add, product, contacde};
                DefaultTableModel tbmodel = (DefaultTableModel) suppliershowtable.getModel();
                tbmodel.addRow(custb);

                suppliershowtable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
                suppliershowtable.getTableHeader().setOpaque(false);
                suppliershowtable.getTableHeader().setBackground(new Color(32, 136, 203));
                suppliershowtable.getTableHeader().setForeground(new Color(0, 0, 0));
                suppliershowtable.setRowHeight(25);

            }
            con.close();

        } catch (SQLException ex) {
            Logger.getLogger(supplier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sup1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        addSuplier = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        suplierReport = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        deletesuplier = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        updatesuplier = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        sup1_AddPane = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        btnGoBack = new javax.swing.JButton();
        btnAddCus = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        IDtag = new javax.swing.JLabel();
        Nametag = new javax.swing.JLabel();
        txtsuppid = new javax.swing.JTextField();
        addresstag = new javax.swing.JLabel();
        txtcusaddre = new javax.swing.JTextField();
        txtproduct = new javax.swing.JTextField();
        businetag = new javax.swing.JLabel();
        infotag = new javax.swing.JLabel();
        txtcontinfo = new javax.swing.JTextField();
        txtsuppname = new javax.swing.JTextField();
        sup1_DeletePane = new javax.swing.JPanel();
        header1 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        btnGoBack1 = new javax.swing.JButton();
        lblimagename1 = new javax.swing.JLabel();
        btnDeleteCus = new javax.swing.JButton();
        btnreset1 = new javax.swing.JButton();
        txtsupid2 = new javax.swing.JTextField();
        IDtag2 = new javax.swing.JLabel();
        txtsupname2 = new javax.swing.JTextField();
        Nametag2 = new javax.swing.JLabel();
        addresstag2 = new javax.swing.JLabel();
        txtcusaddre2 = new javax.swing.JTextField();
        txtproduct2 = new javax.swing.JTextField();
        businetag2 = new javax.swing.JLabel();
        infotag2 = new javax.swing.JLabel();
        txtcontinfo2 = new javax.swing.JTextField();
        sup1_UpdatePane = new javax.swing.JPanel();
        header2 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        btnGoBack2 = new javax.swing.JButton();
        lblimagename2 = new javax.swing.JLabel();
        btnUpdateCus = new javax.swing.JButton();
        btnreset2 = new javax.swing.JButton();
        txtsupid1 = new javax.swing.JTextField();
        IDtag1 = new javax.swing.JLabel();
        Nametag1 = new javax.swing.JLabel();
        txtsupname1 = new javax.swing.JTextField();
        txtcusaddre1 = new javax.swing.JTextField();
        addresstag1 = new javax.swing.JLabel();
        businetag1 = new javax.swing.JLabel();
        txtproduct1 = new javax.swing.JTextField();
        txtcontinfo1 = new javax.swing.JTextField();
        infotag1 = new javax.swing.JLabel();
        sup1_ReportPane = new javax.swing.JPanel();
        header3 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        btnGoBack3 = new javax.swing.JButton();
        lblimagename3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        suppliershowtable = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sup1.setBackground(new java.awt.Color(180, 170, 255));
        sup1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 204)));
        sup1.setPreferredSize(new java.awt.Dimension(820, 700));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setText("Suplier Section");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/icons/information.png"))); // NOI18N
        jLabel15.setToolTipText("");

        addSuplier.setBackground(new java.awt.Color(255, 255, 255));
        addSuplier.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 51, 51)));
        addSuplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addSuplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addSuplierMouseClicked(evt);
            }
        });
        addSuplier.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/icons/c1.png"))); // NOI18N
        addSuplier.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 204, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Add Suplier");
        addSuplier.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 20));

        suplierReport.setBackground(new java.awt.Color(255, 255, 255));
        suplierReport.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 51, 51)));
        suplierReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suplierReportMouseClicked(evt);
            }
        });
        suplierReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/icons/c4.png"))); // NOI18N
        suplierReport.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Suplier Report");
        suplierReport.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, 20));

        deletesuplier.setBackground(new java.awt.Color(255, 255, 255));
        deletesuplier.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 51, 51)));
        deletesuplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletesuplierMouseClicked(evt);
            }
        });
        deletesuplier.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/icons/c2.png"))); // NOI18N
        deletesuplier.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Delete Suplier");
        deletesuplier.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, 20));

        updatesuplier.setBackground(new java.awt.Color(255, 255, 255));
        updatesuplier.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 51, 51)));
        updatesuplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatesuplierMouseClicked(evt);
            }
        });
        updatesuplier.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/icons/c3.png"))); // NOI18N
        updatesuplier.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 0, 204));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Update Suplier");
        updatesuplier.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, 20));

        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 0, 1, new java.awt.Color(0, 0, 0)));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Welcome to Invoice System");

        javax.swing.GroupLayout sup1Layout = new javax.swing.GroupLayout(sup1);
        sup1.setLayout(sup1Layout);
        sup1Layout.setHorizontalGroup(
            sup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sup1Layout.createSequentialGroup()
                .addGroup(sup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sup1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(sup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(sup1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel14)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel15))))
                    .addGroup(sup1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(sup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(suplierReport, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(sup1Layout.createSequentialGroup()
                                .addComponent(addSuplier, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(deletesuplier, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57)
                        .addComponent(updatesuplier, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sup1Layout.setVerticalGroup(
            sup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sup1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(sup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(40, 40, 40)
                .addGroup(sup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addSuplier, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletesuplier, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatesuplier, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(suplierReport, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(sup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        sup1_AddPane.setBackground(new java.awt.Color(200, 210, 255));
        sup1_AddPane.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 204, 204)));
        sup1_AddPane.setToolTipText("");
        sup1_AddPane.setPreferredSize(new java.awt.Dimension(810, 712));
        sup1_AddPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(0, 0, 104));
        header.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Add Suplier:");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addContainerGap(727, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        sup1_AddPane.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, -1));

        btnGoBack.setBackground(new java.awt.Color(255, 0, 51));
        btnGoBack.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnGoBack.setForeground(new java.awt.Color(255, 255, 255));
        btnGoBack.setText("Go Back");
        btnGoBack.setBorderPainted(false);
        btnGoBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });
        sup1_AddPane.add(btnGoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, 170, 30));

        btnAddCus.setBackground(new java.awt.Color(0, 0, 102));
        btnAddCus.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnAddCus.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCus.setText("Add Suplier");
        btnAddCus.setBorderPainted(false);
        btnAddCus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCusActionPerformed(evt);
            }
        });
        sup1_AddPane.add(btnAddCus, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 660, 170, 30));

        btnreset.setBackground(new java.awt.Color(255, 153, 0));
        btnreset.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnreset.setForeground(new java.awt.Color(255, 255, 255));
        btnreset.setText("Reset");
        btnreset.setBorderPainted(false);
        btnreset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        sup1_AddPane.add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 660, 170, 30));

        IDtag.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        IDtag.setForeground(new java.awt.Color(51, 51, 51));
        IDtag.setText("Supplier ID:");
        sup1_AddPane.add(IDtag, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 110, 20));

        Nametag.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Nametag.setForeground(new java.awt.Color(51, 51, 51));
        Nametag.setText("Supplier Name :");
        sup1_AddPane.add(Nametag, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 140, 30));

        txtsuppid.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtsuppid.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtsuppid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsuppidKeyPressed(evt);
            }
        });
        sup1_AddPane.add(txtsuppid, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 360, 40));

        addresstag.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        addresstag.setForeground(new java.awt.Color(51, 51, 51));
        addresstag.setText("Address :");
        sup1_AddPane.add(addresstag, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 90, 30));

        txtcusaddre.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtcusaddre.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtcusaddre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcusaddreKeyPressed(evt);
            }
        });
        sup1_AddPane.add(txtcusaddre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 360, 40));

        txtproduct.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtproduct.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtproduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtproductKeyPressed(evt);
            }
        });
        sup1_AddPane.add(txtproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 360, 40));

        businetag.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        businetag.setForeground(new java.awt.Color(51, 51, 51));
        businetag.setText("Products :");
        sup1_AddPane.add(businetag, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        infotag.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        infotag.setForeground(new java.awt.Color(51, 51, 51));
        infotag.setText("Contact Information :");
        sup1_AddPane.add(infotag, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        txtcontinfo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtcontinfo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtcontinfo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcontinfoKeyPressed(evt);
            }
        });
        sup1_AddPane.add(txtcontinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 360, 40));

        txtsuppname.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtsuppname.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtsuppname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsuppnameKeyPressed(evt);
            }
        });
        sup1_AddPane.add(txtsuppname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 360, 40));

        add(sup1_AddPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 700));

        sup1_DeletePane.setBackground(new java.awt.Color(200, 210, 255));
        sup1_DeletePane.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 204, 204)));
        sup1_DeletePane.setToolTipText("");
        sup1_DeletePane.setPreferredSize(new java.awt.Dimension(810, 712));
        sup1_DeletePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header1.setBackground(new java.awt.Color(0, 0, 104));
        header1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Delete Suplier :");

        javax.swing.GroupLayout header1Layout = new javax.swing.GroupLayout(header1);
        header1.setLayout(header1Layout);
        header1Layout.setHorizontalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addContainerGap(714, Short.MAX_VALUE))
        );
        header1Layout.setVerticalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        sup1_DeletePane.add(header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, -1));

        btnGoBack1.setBackground(new java.awt.Color(255, 0, 51));
        btnGoBack1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnGoBack1.setForeground(new java.awt.Color(255, 255, 255));
        btnGoBack1.setText("Go Back");
        btnGoBack1.setBorderPainted(false);
        btnGoBack1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBack1ActionPerformed(evt);
            }
        });
        sup1_DeletePane.add(btnGoBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, 170, 30));

        lblimagename1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sup1_DeletePane.add(lblimagename1, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 470, 250, 20));

        btnDeleteCus.setBackground(new java.awt.Color(0, 0, 102));
        btnDeleteCus.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnDeleteCus.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteCus.setText("Delete Suplier");
        btnDeleteCus.setBorderPainted(false);
        btnDeleteCus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCusActionPerformed(evt);
            }
        });
        sup1_DeletePane.add(btnDeleteCus, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 660, 170, 30));

        btnreset1.setBackground(new java.awt.Color(255, 153, 0));
        btnreset1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnreset1.setForeground(new java.awt.Color(255, 255, 255));
        btnreset1.setText("Reset");
        btnreset1.setBorderPainted(false);
        btnreset1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreset1ActionPerformed(evt);
            }
        });
        sup1_DeletePane.add(btnreset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 660, 170, 30));

        txtsupid2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtsupid2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtsupid2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsupid2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsupid2KeyReleased(evt);
            }
        });
        sup1_DeletePane.add(txtsupid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 360, 40));

        IDtag2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        IDtag2.setForeground(new java.awt.Color(51, 51, 51));
        IDtag2.setText("Supplier ID:");
        sup1_DeletePane.add(IDtag2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 100, 20));

        txtsupname2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtsupname2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        sup1_DeletePane.add(txtsupname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 360, 40));

        Nametag2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Nametag2.setForeground(new java.awt.Color(51, 51, 51));
        Nametag2.setText("Supplier Name :");
        sup1_DeletePane.add(Nametag2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 140, 30));

        addresstag2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        addresstag2.setForeground(new java.awt.Color(51, 51, 51));
        addresstag2.setText("Address :");
        sup1_DeletePane.add(addresstag2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 90, 30));

        txtcusaddre2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtcusaddre2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        sup1_DeletePane.add(txtcusaddre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 360, 40));

        txtproduct2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtproduct2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        sup1_DeletePane.add(txtproduct2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 360, 40));

        businetag2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        businetag2.setForeground(new java.awt.Color(51, 51, 51));
        businetag2.setText("Products :");
        sup1_DeletePane.add(businetag2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        infotag2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        infotag2.setForeground(new java.awt.Color(51, 51, 51));
        infotag2.setText("Contact Information :");
        sup1_DeletePane.add(infotag2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        txtcontinfo2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtcontinfo2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        sup1_DeletePane.add(txtcontinfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 360, 40));

        add(sup1_DeletePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 700));

        sup1_UpdatePane.setBackground(new java.awt.Color(200, 210, 255));
        sup1_UpdatePane.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 204, 204)));
        sup1_UpdatePane.setToolTipText("");
        sup1_UpdatePane.setPreferredSize(new java.awt.Dimension(810, 712));
        sup1_UpdatePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header2.setBackground(new java.awt.Color(0, 0, 104));
        header2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Update Suplier :");

        javax.swing.GroupLayout header2Layout = new javax.swing.GroupLayout(header2);
        header2.setLayout(header2Layout);
        header2Layout.setHorizontalGroup(
            header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addContainerGap(708, Short.MAX_VALUE))
        );
        header2Layout.setVerticalGroup(
            header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        sup1_UpdatePane.add(header2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, -1));

        btnGoBack2.setBackground(new java.awt.Color(255, 0, 51));
        btnGoBack2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnGoBack2.setForeground(new java.awt.Color(255, 255, 255));
        btnGoBack2.setText("Go Back");
        btnGoBack2.setBorderPainted(false);
        btnGoBack2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBack2ActionPerformed(evt);
            }
        });
        sup1_UpdatePane.add(btnGoBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, 170, 30));

        lblimagename2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sup1_UpdatePane.add(lblimagename2, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 470, 250, 20));

        btnUpdateCus.setBackground(new java.awt.Color(0, 0, 102));
        btnUpdateCus.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnUpdateCus.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateCus.setText("Update Suplier");
        btnUpdateCus.setBorderPainted(false);
        btnUpdateCus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCusActionPerformed(evt);
            }
        });
        sup1_UpdatePane.add(btnUpdateCus, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 660, 170, 30));

        btnreset2.setBackground(new java.awt.Color(255, 153, 0));
        btnreset2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnreset2.setForeground(new java.awt.Color(255, 255, 255));
        btnreset2.setText("Reset");
        btnreset2.setBorderPainted(false);
        btnreset2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreset2ActionPerformed(evt);
            }
        });
        sup1_UpdatePane.add(btnreset2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 660, 170, 30));

        txtsupid1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtsupid1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtsupid1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsupid1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsupid1KeyReleased(evt);
            }
        });
        sup1_UpdatePane.add(txtsupid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 360, 40));

        IDtag1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        IDtag1.setForeground(new java.awt.Color(51, 51, 51));
        IDtag1.setText("Supplier ID:");
        sup1_UpdatePane.add(IDtag1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 100, 20));

        Nametag1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Nametag1.setForeground(new java.awt.Color(51, 51, 51));
        Nametag1.setText("Supplier Name :");
        sup1_UpdatePane.add(Nametag1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 140, 30));

        txtsupname1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtsupname1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtsupname1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsupname1KeyPressed(evt);
            }
        });
        sup1_UpdatePane.add(txtsupname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 360, 40));

        txtcusaddre1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtcusaddre1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtcusaddre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcusaddre1KeyPressed(evt);
            }
        });
        sup1_UpdatePane.add(txtcusaddre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 360, 40));

        addresstag1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        addresstag1.setForeground(new java.awt.Color(51, 51, 51));
        addresstag1.setText("Address :");
        sup1_UpdatePane.add(addresstag1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 90, 30));

        businetag1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        businetag1.setForeground(new java.awt.Color(51, 51, 51));
        businetag1.setText("Products :");
        sup1_UpdatePane.add(businetag1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        txtproduct1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtproduct1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtproduct1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtproduct1KeyPressed(evt);
            }
        });
        sup1_UpdatePane.add(txtproduct1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 360, 40));

        txtcontinfo1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtcontinfo1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtcontinfo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcontinfo1KeyPressed(evt);
            }
        });
        sup1_UpdatePane.add(txtcontinfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 360, 40));

        infotag1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        infotag1.setForeground(new java.awt.Color(51, 51, 51));
        infotag1.setText("COntact Information :");
        sup1_UpdatePane.add(infotag1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        add(sup1_UpdatePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 700));

        sup1_ReportPane.setBackground(new java.awt.Color(200, 210, 255));
        sup1_ReportPane.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 204, 204)));
        sup1_ReportPane.setToolTipText("");
        sup1_ReportPane.setPreferredSize(new java.awt.Dimension(810, 712));
        sup1_ReportPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header3.setBackground(new java.awt.Color(0, 0, 104));
        header3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Report :");

        javax.swing.GroupLayout header3Layout = new javax.swing.GroupLayout(header3);
        header3.setLayout(header3Layout);
        header3Layout.setHorizontalGroup(
            header3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel41)
                .addContainerGap(771, Short.MAX_VALUE))
        );
        header3Layout.setVerticalGroup(
            header3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        sup1_ReportPane.add(header3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, -1));

        btnGoBack3.setBackground(new java.awt.Color(255, 0, 51));
        btnGoBack3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnGoBack3.setForeground(new java.awt.Color(255, 255, 255));
        btnGoBack3.setText("Go Back");
        btnGoBack3.setBorderPainted(false);
        btnGoBack3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBack3ActionPerformed(evt);
            }
        });
        sup1_ReportPane.add(btnGoBack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, 170, 30));

        lblimagename3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sup1_ReportPane.add(lblimagename3, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 470, 250, 20));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        suppliershowtable.setBackground(new java.awt.Color(122, 204, 255));
        suppliershowtable.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 204, 204)));
        suppliershowtable.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        suppliershowtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SUPPLIER NAME", "SUPPLIER ID", "ADDRESS", "PRODUCTS", "CONTACT DETAILS"
            }
        ));
        suppliershowtable.setSelectionBackground(new java.awt.Color(102, 40, 204));
        suppliershowtable.setSelectionForeground(new java.awt.Color(204, 255, 255));
        jScrollPane1.setViewportView(suppliershowtable);

        sup1_ReportPane.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 780, 380));

        add(sup1_ReportPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void addSuplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSuplierMouseClicked
        // TODO add your handling code here:
        sup1_AddPane.setVisible(true);
        sup1_DeletePane.setVisible(false);
        sup1_UpdatePane.setVisible(false);
        sup1_ReportPane.setVisible(false);

        sup1.setVisible(false);
    }//GEN-LAST:event_addSuplierMouseClicked

    private void suplierReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suplierReportMouseClicked
        sup1_AddPane.setVisible(false);
        sup1_DeletePane.setVisible(false);
        sup1_UpdatePane.setVisible(false);
        sup1_ReportPane.setVisible(true);

        sup1.setVisible(false);
    }//GEN-LAST:event_suplierReportMouseClicked

    private void deletesuplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletesuplierMouseClicked
        // TODO add your handling code here:
        sup1_AddPane.setVisible(false);
        sup1_DeletePane.setVisible(true);
        sup1_UpdatePane.setVisible(false);
        sup1_ReportPane.setVisible(false);

        sup1.setVisible(false);
    }//GEN-LAST:event_deletesuplierMouseClicked

    private void updatesuplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatesuplierMouseClicked
        // TODO add your handling code here:
        sup1_AddPane.setVisible(false);
        sup1_DeletePane.setVisible(false);
        sup1_UpdatePane.setVisible(true);
        sup1_ReportPane.setVisible(false);

        sup1.setVisible(false);
    }//GEN-LAST:event_updatesuplierMouseClicked

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        // TODO add your handling code here:
        sup1_AddPane.setVisible(false);
        sup1_DeletePane.setVisible(false);
        sup1_UpdatePane.setVisible(false);
        sup1_ReportPane.setVisible(false);

        sup1.setVisible(true);
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void btnAddCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCusActionPerformed
        if (txtsuppid.getText().isEmpty()) {
            txtsuppid.setBackground(new Color(255, 0, 51));
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else if (txtcusaddre.getText().isEmpty()) {
            txtcusaddre.setBackground(new Color(255, 0, 51));
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else if (txtproduct.getText().isEmpty()) {
            txtproduct.setBackground(new Color(255, 0, 51));
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else if (txtcontinfo.getText().isEmpty()) {
            txtcontinfo.setBackground(new Color(255, 0, 51));
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else {
            int opt = JOptionPane.showConfirmDialog(null, "Are you sure to add this record!!", "Add Record", JOptionPane.YES_NO_OPTION);
            if (opt == 0) {
                try {
                    String query = "insert into suppliers "
                            + "(supplier_name,supplierid,address,products,contactinfo)"
                            + "values (?,?,?,?,?)";

                    con = DriverManager.getConnection("jdbc:mysql://localhost/sr_bio_foods", "root", "");
                    pst = con.prepareStatement(query);

                    pst.setString(1, txtsuppname.getText());
                    pst.setString(2, txtsuppid.getText());
                    pst.setString(3, txtcusaddre.getText());
                    pst.setString(4, txtproduct.getText());
                    pst.setString(5, txtcontinfo.getText());
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Add Successfull");
                    txtsuppid.setText("");
                    txtsuppname.setText("");
                    txtcusaddre.setText("");
                    txtproduct.setText("");
                    txtcontinfo.setText("");
                    autoidgen();
                } catch (SQLException ex) {
                    Logger.getLogger(supplier.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        showtable();
    }//GEN-LAST:event_btnAddCusActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        txtsuppid.setText("");
        autoidgen();
        txtcusaddre.setText("");
        txtproduct.setText("");
        txtcontinfo.setText("");

    }//GEN-LAST:event_btnresetActionPerformed

    private void btnGoBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBack1ActionPerformed
        sup1_AddPane.setVisible(false);
        sup1_DeletePane.setVisible(false);
        sup1_UpdatePane.setVisible(false);
        sup1_ReportPane.setVisible(false);

        sup1.setVisible(true);
    }//GEN-LAST:event_btnGoBack1ActionPerformed

    private void btnDeleteCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCusActionPerformed
        if (txtsupname2.getText().isEmpty()) {
            txtsupname2.setBackground(new Color(255, 0, 51));
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else if (txtsupid2.getText().isEmpty()) {
            txtsupid2.setBackground(new Color(255, 0, 51));
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else if (txtcusaddre2.getText().isEmpty()) {
            txtcusaddre2.setBackground(new Color(255, 0, 51));
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else if (txtproduct2.getText().isEmpty()) {
            txtproduct2.setBackground(new Color(255, 0, 51));
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else if (txtcontinfo2.getText().isEmpty()) {
            txtcontinfo2.setBackground(new Color(255, 0, 51));
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else {

            int opt = JOptionPane.showConfirmDialog(null, "Are you sure to Delete !!", "Delete", JOptionPane.YES_NO_OPTION);
            if (opt == 0) {
                try {
                    String query = "delete from suppliers where supplierid = ?";
                    con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/sr_bio_foods", "root", "");
                    pst = con.prepareStatement(query);
                    pst.setString(1, txtsupid2.getText());
                    pst.executeUpdate();

                    JOptionPane.showMessageDialog(null, "DELETE SUCCESSFULLY");
                    txtsupname2.setText("");
                    txtsupid2.setText("");
                    txtcusaddre2.setText("");
                    txtproduct2.setText("");
                    txtcontinfo2.setText("");
                    showtable();

                } catch (SQLException ex) {
                    Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }

    }//GEN-LAST:event_btnDeleteCusActionPerformed

    private void btnreset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreset1ActionPerformed
        txtsupname2.setText("");
        txtsupid2.setText("");
        txtcusaddre2.setText("");
        txtproduct2.setText("");
        txtcontinfo2.setText("");
    }//GEN-LAST:event_btnreset1ActionPerformed

    private void btnGoBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBack2ActionPerformed
        sup1_AddPane.setVisible(false);
        sup1_DeletePane.setVisible(false);
        sup1_UpdatePane.setVisible(false);
        sup1_ReportPane.setVisible(false);

        sup1.setVisible(true);
    }//GEN-LAST:event_btnGoBack2ActionPerformed

    private void btnUpdateCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCusActionPerformed
        if (txtsupname1.getText().isEmpty()) {
            txtsupname1.setBackground(new Color(255, 0, 51));
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else if (txtsupid1.getText().isEmpty()) {
            txtsupid1.setBackground(new Color(255, 0, 51));
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else if (txtcusaddre1.getText().isEmpty()) {
            txtcusaddre1.setBackground(new Color(255, 0, 51));
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else if (txtproduct1.getText().isEmpty()) {
            txtproduct1.setBackground(new Color(255, 0, 51));
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else if (txtcontinfo1.getText().isEmpty()) {
            txtcontinfo1.setBackground(new Color(255, 0, 51));
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else {
            int opt = JOptionPane.showConfirmDialog(null, "Are you sure to Update this record!!", "Update Record", JOptionPane.YES_NO_OPTION);
            if (opt == 0) {

                try {
                    String sql = "UPDATE suppliers SET supplier_name=?,address=?,products=?,contactinfo=? WHERE supplierid= '" + txtsupid1.getText() + "'";
                    con = DriverManager.getConnection("jdbc:mysql://localhost/sr_bio_foods", "root", "");
                    pst = con.prepareStatement(sql);

                    pst.setString(1, txtsupname1.getText());
                    pst.setString(2, txtcusaddre1.getText());
                    pst.setString(3, txtproduct1.getText());
                    pst.setString(4, txtcontinfo1.getText());

                    pst.executeUpdate();

                    JOptionPane.showMessageDialog(null, "UPDATE SUCCESSFULLY");
                    txtsupname1.setText("");
                    txtsupid1.setText("");
                    txtcusaddre1.setText("");
                    txtproduct1.setText("");
                    txtcontinfo1.setText("");

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());

                }
            }
        }
        showtable();

    }//GEN-LAST:event_btnUpdateCusActionPerformed

    private void btnreset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreset2ActionPerformed
        txtsupname1.setText("");
        txtsupid1.setText("");
        txtcusaddre1.setText("");
        txtproduct1.setText("");
        txtcontinfo1.setText("");
    }//GEN-LAST:event_btnreset2ActionPerformed

    private void btnGoBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBack3ActionPerformed
        sup1_AddPane.setVisible(false);
        sup1_DeletePane.setVisible(false);
        sup1_UpdatePane.setVisible(false);
        sup1_ReportPane.setVisible(false);

        sup1.setVisible(true);
    }//GEN-LAST:event_btnGoBack3ActionPerformed

    private void txtsupid1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsupid1KeyPressed
        txtsupid1.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_txtsupid1KeyPressed

    private void txtsupid1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsupid1KeyReleased
        txtsupid1.setBackground(new Color(255, 255, 255));
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        try {

            String sql1 = "select * from suppliers where supplierid = ?";
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/sr_bio_foods", "root", "");
            pst = (PreparedStatement) con.prepareStatement(sql1);
            String suid = txtsupid2.getText();
            pst.setString(1, suid);
            rs = (ResultSet) pst.executeQuery();
            if (rs.next()) {

                String supname = rs.getString("supplier_name");
                txtsupname2.setText(supname.trim());
                String addr = rs.getString("address");
                txtcusaddre2.setText(addr.trim());
                String product = rs.getString("products");
                txtproduct2.setText(product.trim());
                String coin = rs.getString("contactinfo");
                txtcontinfo2.setText(coin.trim());
            }

        } catch (SQLException ex) {
            Logger.getLogger(supplier.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_txtsupid1KeyReleased

    private void txtsupid2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsupid2KeyPressed

    }//GEN-LAST:event_txtsupid2KeyPressed

    private void txtsupid2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsupid2KeyReleased
        txtsupid2.setBackground(new Color(255, 255, 255));
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        try {

            String sql1 = "select * from suppliers where supplierid = ?";
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/sr_bio_foods", "root", "");
            pst = (PreparedStatement) con.prepareStatement(sql1);
            String suid = txtsupid2.getText();
            pst.setString(1, suid);
            rs = (ResultSet) pst.executeQuery();
            if (rs.next() == false) {

                txtsupname2.setText("");
                txtsupid2.setText("");
                txtcusaddre2.setText("");
                txtproduct2.setText("");
                txtcontinfo2.setText("");
            } else {
                String supname = rs.getString("supplier_name");
                txtsupname2.setText(supname.trim());
                String addr = rs.getString("address");
                txtcusaddre2.setText(addr.trim());
                String product = rs.getString("products");
                txtproduct2.setText(product.trim());
                String coin = rs.getString("contactinfo");
                txtcontinfo2.setText(coin.trim());

            }

        } catch (SQLException ex) {
            Logger.getLogger(supplier.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_txtsupid2KeyReleased

    private void txtsuppidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsuppidKeyPressed
        txtsuppid.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_txtsuppidKeyPressed

    private void txtcusaddreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcusaddreKeyPressed
        txtcusaddre.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_txtcusaddreKeyPressed

    private void txtproductKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtproductKeyPressed
        txtproduct.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_txtproductKeyPressed

    private void txtcontinfoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontinfoKeyPressed
        txtcontinfo.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_txtcontinfoKeyPressed

    private void txtsupname1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsupname1KeyPressed
        txtsupname1.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_txtsupname1KeyPressed

    private void txtcusaddre1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcusaddre1KeyPressed
        txtcusaddre1.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_txtcusaddre1KeyPressed

    private void txtproduct1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtproduct1KeyPressed
        txtproduct1.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_txtproduct1KeyPressed

    private void txtcontinfo1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontinfo1KeyPressed
        txtcontinfo1.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_txtcontinfo1KeyPressed

    private void txtsuppnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsuppnameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsuppnameKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDtag;
    private javax.swing.JLabel IDtag1;
    private javax.swing.JLabel IDtag2;
    private javax.swing.JLabel Nametag;
    private javax.swing.JLabel Nametag1;
    private javax.swing.JLabel Nametag2;
    private javax.swing.JPanel addSuplier;
    private javax.swing.JLabel addresstag;
    private javax.swing.JLabel addresstag1;
    private javax.swing.JLabel addresstag2;
    private javax.swing.JButton btnAddCus;
    private javax.swing.JButton btnDeleteCus;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnGoBack1;
    private javax.swing.JButton btnGoBack2;
    private javax.swing.JButton btnGoBack3;
    private javax.swing.JButton btnUpdateCus;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnreset1;
    private javax.swing.JButton btnreset2;
    private javax.swing.JLabel businetag;
    private javax.swing.JLabel businetag1;
    private javax.swing.JLabel businetag2;
    private javax.swing.JPanel deletesuplier;
    private javax.swing.JPanel header;
    private javax.swing.JPanel header1;
    private javax.swing.JPanel header2;
    private javax.swing.JPanel header3;
    private javax.swing.JLabel infotag;
    private javax.swing.JLabel infotag1;
    private javax.swing.JLabel infotag2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblimagename1;
    private javax.swing.JLabel lblimagename2;
    private javax.swing.JLabel lblimagename3;
    private javax.swing.JPanel sup1;
    private javax.swing.JPanel sup1_AddPane;
    private javax.swing.JPanel sup1_DeletePane;
    private javax.swing.JPanel sup1_ReportPane;
    private javax.swing.JPanel sup1_UpdatePane;
    private javax.swing.JPanel suplierReport;
    private javax.swing.JTable suppliershowtable;
    private javax.swing.JTextField txtcontinfo;
    private javax.swing.JTextField txtcontinfo1;
    private javax.swing.JTextField txtcontinfo2;
    private javax.swing.JTextField txtcusaddre;
    private javax.swing.JTextField txtcusaddre1;
    private javax.swing.JTextField txtcusaddre2;
    private javax.swing.JTextField txtproduct;
    private javax.swing.JTextField txtproduct1;
    private javax.swing.JTextField txtproduct2;
    private javax.swing.JTextField txtsupid1;
    private javax.swing.JTextField txtsupid2;
    private javax.swing.JTextField txtsupname1;
    private javax.swing.JTextField txtsupname2;
    private javax.swing.JTextField txtsuppid;
    private javax.swing.JTextField txtsuppname;
    private javax.swing.JPanel updatesuplier;
    // End of variables declaration//GEN-END:variables
}
