/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.management.srb.employee1;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.print.PrinterException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Avishka
 */
public class Leave extends javax.swing.JPanel {
    
    Connection con = null;
    PreparedStatement pst1;
    PreparedStatement pst2;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement st=null;
    /**
     * Creates new form Leave
     */
     String status;
    String imageFilePath ;
    String imageFileName ;
    InputStream inputstream ;
    InputStream upinputstream ;
    InputStream barcodeinputstream ;
    String barcodeFilePath ;
    String captureFilePath ;
    String gender ;
    String upimageFilePath;
    String upimageFileName;
    String x;
    String casual ;
    String annual ;
    String medical ;
    String year ;
    String emp;
    String NIC;
    int days;
    int casual1 ;
    int annual1;
    int medical1;
    String leave;
    
    
    
    
    public Leave() {
        initComponents();
        
    tablelord2();  
    
      p4_leaveschedule.setVisible(false);
        p4_empleave.setVisible(false);
        p4_leavereport.setVisible(false);
    
        p4.setVisible(true);
       
    
    
    }
    
   
                    
                    
   
         private void tablelord2()
       
        {
               
                    
             
              try
              {
                  String sql="SELECT `EmpNo`, `NIC_No`, `Casual_Leaves`, `Annual_Leaves`, `Medical_Leaves`, Additional_Leaves,`Year` FROM `leaveinformation`";
                con = DriverManager.getConnection("jdbc:mysql://localhost/sr_bio_foods", "root", "");
                pst=(PreparedStatement) con.prepareStatement(sql);
              
                    ResultSet rs= pst.executeQuery();
                     EMPleavereport.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
                     EMPleavereport.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,14));
                     EMPleavereport.getTableHeader().setOpaque(false);
                     EMPleavereport.getTableHeader().setBackground(new Color(32,136,203));
                     EMPleavereport.getTableHeader().setForeground(new Color(0,0,0));
                     EMPleavereport.setRowHeight(25);
                     EMPleavereport.getColumnModel().getColumn(0).setPreferredWidth(100); 
                     EMPleavereport.getColumnModel().getColumn(1).setPreferredWidth(150); 
                    EMPleavereport.getColumnModel().getColumn(2).setPreferredWidth(120); 
                    EMPleavereport.getColumnModel().getColumn(3).setPreferredWidth(120); 
                    EMPleavereport.getColumnModel().getColumn(4).setPreferredWidth(120); 
                    EMPleavereport.getColumnModel().getColumn(5).setPreferredWidth(160); 
                    EMPleavereport.getColumnModel().getColumn(6).setPreferredWidth(100); 
                  
                    
                    
                    
                    
                   }
                     catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
                    
                   }
              
                    
        }
              
                   
                       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p4 = new javax.swing.JPanel();
        btnemployeeleave = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        deleteEmployee1 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        deleteEmployee2 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        p4_empleave = new javax.swing.JPanel();
        header5 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        lblemono4 = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lblimageleave = new javax.swing.JLabel();
        txtempno5 = new javax.swing.JTextField();
        lblDepartment4 = new javax.swing.JLabel();
        txtdepartment4 = new javax.swing.JTextField();
        lbldesignation4 = new javax.swing.JLabel();
        txtdesignation4 = new javax.swing.JTextField();
        lbldays = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rmedical = new javax.swing.JRadioButton();
        rcasual = new javax.swing.JRadioButton();
        rannual = new javax.swing.JRadioButton();
        lbladditionalleave = new javax.swing.JLabel();
        btnGoBack5 = new javax.swing.JButton();
        btnaddleave = new javax.swing.JButton();
        btnreset3 = new javax.swing.JButton();
        txtNIC1 = new javax.swing.JTextField();
        lblNIC1 = new javax.swing.JLabel();
        txtdays = new javax.swing.JTextField();
        txtadditionaldays = new javax.swing.JTextField();
        addionaGetbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        p4_leavereport = new javax.swing.JPanel();
        header7 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        btnGoBack7 = new javax.swing.JButton();
        btnaddschedule1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        EMPleavereport = new javax.swing.JTable();
        p4_leaveschedule = new javax.swing.JPanel();
        header6 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        txtyear = new javax.swing.JTextField();
        lblmedicalleave = new javax.swing.JLabel();
        lblannualleave = new javax.swing.JLabel();
        lblcasualleave = new javax.swing.JLabel();
        lblyear = new javax.swing.JLabel();
        btnreset4 = new javax.swing.JButton();
        btnGoBack6 = new javax.swing.JButton();
        btnaddschedule = new javax.swing.JButton();
        jscasualleave = new javax.swing.JTextField();
        jsmedicalleave = new javax.swing.JTextField();
        jsannualleave = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p4.setBackground(new java.awt.Color(180, 170, 255));
        p4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 204)));
        p4.setPreferredSize(new java.awt.Dimension(810, 712));
        p4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnemployeeleave.setBackground(new java.awt.Color(255, 255, 255));
        btnemployeeleave.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 51, 51)));
        btnemployeeleave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnemployeeleave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnemployeeleaveMouseClicked(evt);
            }
        });
        btnemployeeleave.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/icons/empl.png"))); // NOI18N
        btnemployeeleave.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 130, 120));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 102, 0));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("Employee Leave");
        btnemployeeleave.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 130, 130, 20));

        p4.add(btnemployeeleave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 210, 170));

        deleteEmployee1.setBackground(new java.awt.Color(255, 255, 255));
        deleteEmployee1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 51, 51)));
        deleteEmployee1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteEmployee1MouseClicked(evt);
            }
        });
        deleteEmployee1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/icons/leaveshedule.png"))); // NOI18N
        deleteEmployee1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 130, 120));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 102, 204));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Leave Shedule");
        deleteEmployee1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, 20));

        p4.add(deleteEmployee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 210, 170));

        deleteEmployee2.setBackground(new java.awt.Color(255, 255, 255));
        deleteEmployee2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 51, 51)));
        deleteEmployee2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteEmployee2MouseClicked(evt);
            }
        });
        deleteEmployee2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/icons/leave report.png"))); // NOI18N
        deleteEmployee2.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 120, 120));

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 153, 0));
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("Leave report");
        deleteEmployee2.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 100, 20));

        p4.add(deleteEmployee2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 210, 170));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Welcome to EMP System");
        p4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 44, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        p4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 126, 561, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setText("Leave Section");
        p4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 170, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/icons/information.png"))); // NOI18N
        jLabel15.setToolTipText("");
        p4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 710));

        p4_empleave.setBackground(new java.awt.Color(200, 210, 255));
        p4_empleave.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 204, 204)));
        p4_empleave.setToolTipText("");
        p4_empleave.setPreferredSize(new java.awt.Dimension(810, 712));
        p4_empleave.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header5.setBackground(new java.awt.Color(0, 0, 104));
        header5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Employee Leave :");

        javax.swing.GroupLayout header5Layout = new javax.swing.GroupLayout(header5);
        header5.setLayout(header5Layout);
        header5Layout.setHorizontalGroup(
            header5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel45)
                .addContainerGap(668, Short.MAX_VALUE))
        );
        header5Layout.setVerticalGroup(
            header5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        p4_empleave.add(header5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, -1));

        lblemono4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblemono4.setForeground(new java.awt.Color(51, 51, 51));
        lblemono4.setText("Employee No :");
        p4_empleave.add(lblemono4, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 245, -1, -1));

        lblname.setBackground(new java.awt.Color(51, 0, 51));
        lblname.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblname.setForeground(new java.awt.Color(51, 51, 51));
        lblname.setText("Name :");
        p4_empleave.add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 300, -1, -1));

        txtname.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtname.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnameKeyPressed(evt);
            }
        });
        p4_empleave.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 293, 240, 35));

        lblimageleave.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        p4_empleave.add(lblimageleave, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 210, 140));

        txtempno5.setBackground(new java.awt.Color(235, 235, 235));
        txtempno5.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtempno5.setForeground(new java.awt.Color(153, 153, 153));
        txtempno5.setText("              Enter Employee ID to Search");
        txtempno5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtempno5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtempno5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtempno5FocusLost(evt);
            }
        });
        txtempno5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtempno5ActionPerformed(evt);
            }
        });
        txtempno5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtempno5KeyPressed(evt);
            }
        });
        p4_empleave.add(txtempno5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 238, 240, 35));

        lblDepartment4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblDepartment4.setForeground(new java.awt.Color(51, 51, 51));
        lblDepartment4.setText("Department :");
        p4_empleave.add(lblDepartment4, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 410, -1, -1));

        txtdepartment4.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtdepartment4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtdepartment4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdepartment4ActionPerformed(evt);
            }
        });
        txtdepartment4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdepartment4KeyPressed(evt);
            }
        });
        p4_empleave.add(txtdepartment4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 403, 240, 35));

        lbldesignation4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lbldesignation4.setForeground(new java.awt.Color(51, 51, 51));
        lbldesignation4.setText("Designation :");
        p4_empleave.add(lbldesignation4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 465, -1, -1));

        txtdesignation4.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtdesignation4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtdesignation4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdesignation4ActionPerformed(evt);
            }
        });
        txtdesignation4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdesignation4KeyPressed(evt);
            }
        });
        p4_empleave.add(txtdesignation4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 458, 240, 35));

        lbldays.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lbldays.setForeground(new java.awt.Color(51, 51, 51));
        lbldays.setText("Leave Days :");
        p4_empleave.add(lbldays, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 520, -1, -1));

        jPanel1.setBackground(new java.awt.Color(200, 210, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 204)));

        rmedical.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        rmedical.setText("Medical Leave");
        rmedical.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rmedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmedicalActionPerformed(evt);
            }
        });

        rcasual.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        rcasual.setText("Casual Leave");
        rcasual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rcasual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcasualActionPerformed(evt);
            }
        });

        rannual.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        rannual.setText("Annual Leave");
        rannual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rannual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rannualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rmedical, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rannual, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rcasual, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(rcasual, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(rannual, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(rmedical, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        p4_empleave.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 184, -1));

        lbladditionalleave.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lbladditionalleave.setForeground(new java.awt.Color(51, 51, 51));
        lbladditionalleave.setText("Get Additional Leaves ");
        p4_empleave.add(lbladditionalleave, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, -1, -1));

        btnGoBack5.setBackground(new java.awt.Color(255, 0, 51));
        btnGoBack5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnGoBack5.setForeground(new java.awt.Color(255, 255, 255));
        btnGoBack5.setText("Go Back");
        btnGoBack5.setBorderPainted(false);
        btnGoBack5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoBack5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGoBack5MouseClicked(evt);
            }
        });
        btnGoBack5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBack5ActionPerformed(evt);
            }
        });
        btnGoBack5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnGoBack5KeyPressed(evt);
            }
        });
        p4_empleave.add(btnGoBack5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 653, 170, -1));

        btnaddleave.setBackground(new java.awt.Color(0, 0, 102));
        btnaddleave.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnaddleave.setForeground(new java.awt.Color(255, 255, 255));
        btnaddleave.setText("Add Leave");
        btnaddleave.setBorderPainted(false);
        btnaddleave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnaddleave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddleaveActionPerformed(evt);
            }
        });
        p4_empleave.add(btnaddleave, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 649, 170, 30));

        btnreset3.setBackground(new java.awt.Color(204, 102, 0));
        btnreset3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnreset3.setForeground(new java.awt.Color(255, 255, 255));
        btnreset3.setText("Reset");
        btnreset3.setBorderPainted(false);
        btnreset3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreset3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreset3ActionPerformed(evt);
            }
        });
        p4_empleave.add(btnreset3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 649, 170, 30));

        txtNIC1.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtNIC1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtNIC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIC1ActionPerformed(evt);
            }
        });
        txtNIC1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNIC1KeyPressed(evt);
            }
        });
        p4_empleave.add(txtNIC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 348, 240, 35));

        lblNIC1.setBackground(new java.awt.Color(51, 0, 51));
        lblNIC1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblNIC1.setForeground(new java.awt.Color(51, 51, 51));
        lblNIC1.setText("NIC No :");
        p4_empleave.add(lblNIC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 355, -1, -1));

        txtdays.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtdays.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtdays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdaysActionPerformed(evt);
            }
        });
        txtdays.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdaysKeyPressed(evt);
            }
        });
        p4_empleave.add(txtdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 513, 240, 35));

        txtadditionaldays.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtadditionaldays.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtadditionaldays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtadditionaldaysActionPerformed(evt);
            }
        });
        p4_empleave.add(txtadditionaldays, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 190, 30));

        addionaGetbtn.setBackground(new java.awt.Color(0, 0, 102));
        addionaGetbtn.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        addionaGetbtn.setForeground(new java.awt.Color(255, 255, 255));
        addionaGetbtn.setText("Add");
        addionaGetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addionaGetbtnActionPerformed(evt);
            }
        });
        p4_empleave.add(addionaGetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 90, -1));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255), 2));
        p4_empleave.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 250, 140));

        add(p4_empleave, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        p4_leavereport.setBackground(new java.awt.Color(200, 210, 255));
        p4_leavereport.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 204, 204)));
        p4_leavereport.setPreferredSize(new java.awt.Dimension(810, 712));
        p4_leavereport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header7.setBackground(new java.awt.Color(0, 0, 104));
        header7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel53.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Employee Leave Report :");

        javax.swing.GroupLayout header7Layout = new javax.swing.GroupLayout(header7);
        header7.setLayout(header7Layout);
        header7Layout.setHorizontalGroup(
            header7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header7Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel53)
                .addContainerGap(650, Short.MAX_VALUE))
        );
        header7Layout.setVerticalGroup(
            header7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        p4_leavereport.add(header7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -4, 870, 40));

        btnGoBack7.setBackground(new java.awt.Color(255, 0, 51));
        btnGoBack7.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnGoBack7.setForeground(new java.awt.Color(255, 255, 255));
        btnGoBack7.setText("Go Back");
        btnGoBack7.setBorderPainted(false);
        btnGoBack7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoBack7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGoBack7MouseClicked(evt);
            }
        });
        btnGoBack7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBack7ActionPerformed(evt);
            }
        });
        btnGoBack7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnGoBack7KeyPressed(evt);
            }
        });
        p4_leavereport.add(btnGoBack7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 651, 170, 30));

        btnaddschedule1.setBackground(new java.awt.Color(0, 0, 102));
        btnaddschedule1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnaddschedule1.setForeground(new java.awt.Color(255, 255, 255));
        btnaddschedule1.setText("Print");
        btnaddschedule1.setBorderPainted(false);
        btnaddschedule1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnaddschedule1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddschedule1ActionPerformed(evt);
            }
        });
        p4_leavereport.add(btnaddschedule1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 647, 170, 30));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        EMPleavereport.setBackground(new java.awt.Color(122, 204, 255));
        EMPleavereport.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 204, 204)));
        EMPleavereport.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EMPleavereport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        EMPleavereport.setFocusable(false);
        EMPleavereport.setRowHeight(25);
        EMPleavereport.setSelectionBackground(new java.awt.Color(102, 40, 204));
        EMPleavereport.getTableHeader().setResizingAllowed(false);
        EMPleavereport.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(EMPleavereport);

        p4_leavereport.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, 790, 565));

        add(p4_leavereport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 710));

        p4_leaveschedule.setBackground(new java.awt.Color(200, 210, 255));
        p4_leaveschedule.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 204, 204)));
        p4_leaveschedule.setPreferredSize(new java.awt.Dimension(810, 712));

        header6.setBackground(new java.awt.Color(0, 0, 104));
        header6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Employee Leave Schedule :");

        javax.swing.GroupLayout header6Layout = new javax.swing.GroupLayout(header6);
        header6.setLayout(header6Layout);
        header6Layout.setHorizontalGroup(
            header6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel50)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        header6Layout.setVerticalGroup(
            header6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtyear.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtyear.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        txtyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtyearActionPerformed(evt);
            }
        });
        txtyear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtyearKeyPressed(evt);
            }
        });

        lblmedicalleave.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblmedicalleave.setForeground(new java.awt.Color(51, 51, 51));
        lblmedicalleave.setText("Medical Leave");

        lblannualleave.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblannualleave.setForeground(new java.awt.Color(51, 51, 51));
        lblannualleave.setText("Annual Leave :");

        lblcasualleave.setBackground(new java.awt.Color(51, 0, 51));
        lblcasualleave.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblcasualleave.setForeground(new java.awt.Color(51, 51, 51));
        lblcasualleave.setText("Casual Leave :");

        lblyear.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblyear.setForeground(new java.awt.Color(51, 51, 51));
        lblyear.setText(" Year :");

        btnreset4.setBackground(new java.awt.Color(204, 102, 0));
        btnreset4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnreset4.setForeground(new java.awt.Color(255, 255, 255));
        btnreset4.setText("Delete Old Schedule");
        btnreset4.setBorderPainted(false);
        btnreset4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreset4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreset4ActionPerformed(evt);
            }
        });

        btnGoBack6.setBackground(new java.awt.Color(255, 0, 51));
        btnGoBack6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnGoBack6.setForeground(new java.awt.Color(255, 255, 255));
        btnGoBack6.setText("Go Back");
        btnGoBack6.setBorderPainted(false);
        btnGoBack6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoBack6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGoBack6MouseClicked(evt);
            }
        });
        btnGoBack6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBack6ActionPerformed(evt);
            }
        });
        btnGoBack6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnGoBack6KeyPressed(evt);
            }
        });

        btnaddschedule.setBackground(new java.awt.Color(0, 0, 102));
        btnaddschedule.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnaddschedule.setForeground(new java.awt.Color(255, 255, 255));
        btnaddschedule.setText("Add Schedule");
        btnaddschedule.setBorderPainted(false);
        btnaddschedule.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnaddschedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddscheduleActionPerformed(evt);
            }
        });

        jscasualleave.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jscasualleave.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        jscasualleave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jscasualleaveActionPerformed(evt);
            }
        });
        jscasualleave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jscasualleaveKeyPressed(evt);
            }
        });

        jsmedicalleave.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jsmedicalleave.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        jsmedicalleave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsmedicalleaveActionPerformed(evt);
            }
        });
        jsmedicalleave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsmedicalleaveKeyPressed(evt);
            }
        });

        jsannualleave.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jsannualleave.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        jsannualleave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jsannualleaveMouseClicked(evt);
            }
        });
        jsannualleave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsannualleaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p4_leavescheduleLayout = new javax.swing.GroupLayout(p4_leaveschedule);
        p4_leaveschedule.setLayout(p4_leavescheduleLayout);
        p4_leavescheduleLayout.setHorizontalGroup(
            p4_leavescheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4_leavescheduleLayout.createSequentialGroup()
                .addGroup(p4_leavescheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p4_leavescheduleLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(lblcasualleave)
                        .addGap(45, 45, 45)
                        .addComponent(jscasualleave, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p4_leavescheduleLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(lblannualleave)
                        .addGap(42, 42, 42)
                        .addComponent(jsannualleave, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p4_leavescheduleLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(lblmedicalleave)
                        .addGap(44, 44, 44)
                        .addComponent(jsmedicalleave, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p4_leavescheduleLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(lblyear)
                        .addGap(95, 95, 95)
                        .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p4_leavescheduleLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnGoBack6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(btnreset4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(btnaddschedule, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(header6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        p4_leavescheduleLayout.setVerticalGroup(
            p4_leavescheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4_leavescheduleLayout.createSequentialGroup()
                .addComponent(header6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addGroup(p4_leavescheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p4_leavescheduleLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblcasualleave))
                    .addComponent(jscasualleave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(p4_leavescheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p4_leavescheduleLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblannualleave))
                    .addComponent(jsannualleave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(p4_leavescheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p4_leavescheduleLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblmedicalleave))
                    .addComponent(jsmedicalleave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(p4_leavescheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p4_leavescheduleLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblyear))
                    .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(218, 218, 218)
                .addGroup(p4_leavescheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnaddschedule, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnreset4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGoBack6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        add(p4_leaveschedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 710));
    }// </editor-fold>//GEN-END:initComponents

    private void btnemployeeleaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnemployeeleaveMouseClicked
        // TODO add your handling code here:
        p4_empleave.setVisible(true);
       
        p4_leaveschedule.setVisible(false);
        p4_leavereport.setVisible(false);
      
        p4.setVisible(false);
        
    }//GEN-LAST:event_btnemployeeleaveMouseClicked

    private void deleteEmployee1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteEmployee1MouseClicked
        // TODO add your handling code here:
      
        p4_leaveschedule.setVisible(true);
        p4_empleave.setVisible(false);
        p4_leavereport.setVisible(false);

      
        p4.setVisible(false);
      

    }//GEN-LAST:event_deleteEmployee1MouseClicked

    private void deleteEmployee2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteEmployee2MouseClicked
        // TODO add your handling code here:
        tablelord2();
        p4_leavereport.setVisible(true);
       
        p4_leaveschedule.setVisible(false);
        p4_empleave.setVisible(false);

      
        p4.setVisible(false);
       
    }//GEN-LAST:event_deleteEmployee2MouseClicked

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyPressed
        // TODO add your handling code here:
        txtname.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_txtnameKeyPressed

    private void txtempno5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtempno5FocusGained
        // TODO add your handling code here:
        if(txtempno5.getText().trim().equals("Enter Employee ID to Search")) {
            txtempno5.setText("");
            txtempno5.setForeground(new Color(153,153,153));
        }
        txtempno5.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtempno5FocusGained

    private void txtempno5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtempno5FocusLost
        // TODO add your handling code here:
        if(txtempno5.getText().trim().equals("")){
            txtempno5.setText("             Enter Employee ID to Search");
        }
    }//GEN-LAST:event_txtempno5FocusLost

    private void txtempno5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtempno5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtempno5ActionPerformed

    private void txtempno5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtempno5KeyPressed
        // TODO add your handling code here:
        try {
            String sql ="SELECT * FROM employee where EmpNo=? ";
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/sr_bio_foods", "root", "");
            pst=(PreparedStatement) con.prepareStatement(sql);

            pst.setString(1, txtempno5.getText());
            rs= (ResultSet) pst.executeQuery();
            if(rs.next()) {
                txtempno5.setText(rs.getString("EmpNo"));
                txtNIC1.setText(rs.getString("NIC_No"));
                txtname.setText(rs.getString("First_Name"));

                txtdepartment4.setText(rs.getString("Department"));

                txtdesignation4.setText(rs.getString("Designation"));

                byte[] img = rs.getBytes("Profile_Pic");
                ImageIcon proimage = new ImageIcon(img);
                Image im = proimage.getImage();
                Image myImg = im.getScaledInstance(lblimageleave.getWidth(), lblimageleave.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myImg);
                lblimageleave.setIcon(newImage);

            }
        }

        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        txtempno5.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_txtempno5KeyPressed

    private void txtdepartment4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdepartment4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdepartment4ActionPerformed

    private void txtdepartment4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdepartment4KeyPressed
        // TODO add your handling code here:
        txtdepartment4.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_txtdepartment4KeyPressed

    private void txtdesignation4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdesignation4ActionPerformed
        // TODO add your handling code here:
        txtdesignation4.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_txtdesignation4ActionPerformed

    private void txtdesignation4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdesignation4KeyPressed
        // TODO add your handling code here:
        txtname.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_txtdesignation4KeyPressed

    private void rmedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmedicalActionPerformed
        // TODO add your handling code here:
        status = "Medical";
        rcasual.setSelected(false);
        rannual.setSelected(false);
        rmedical.setSelected(true);
        if(rmedical.isSelected())
        {
            rmedical.setForeground(new java.awt.Color(0,0,0));
            rannual.setForeground(new java.awt.Color(0,0,0));
            rcasual.setForeground(new java.awt.Color(0,0,0));
            rannual.setSelected(false);
            rcasual.setSelected(false);
        }
    }//GEN-LAST:event_rmedicalActionPerformed

    private void rcasualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcasualActionPerformed
        // TODO add your handling code here:
        status = "Casual";
        rcasual.setSelected(true);
        rannual.setSelected(false);
        rmedical.setSelected(false);
        if(rcasual.isSelected())
        {
            rmedical.setForeground(new java.awt.Color(0,0,0));
            rannual.setForeground(new java.awt.Color(0,0,0));
            rcasual.setForeground(new java.awt.Color(0,0,0));
            rmedical.setSelected(false);
            rannual.setSelected(false);
        }
    }//GEN-LAST:event_rcasualActionPerformed

    private void rannualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rannualActionPerformed
        // TODO add your handling code here:
        status = "Annual";
        rcasual.setSelected(false);
        rannual.setSelected(true);
        rmedical.setSelected(false);
        if(rannual.isSelected())
        {
            rmedical.setForeground(new java.awt.Color(0,0,0));
            rannual.setForeground(new java.awt.Color(0,0,0));
            rcasual.setForeground(new java.awt.Color(0,0,0));
            rmedical.setSelected(false);
            rcasual.setSelected(false);
        }
    }//GEN-LAST:event_rannualActionPerformed

    private void btnGoBack5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGoBack5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoBack5MouseClicked

    private void btnGoBack5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBack5ActionPerformed
        // TODO add your handling code here:
      
        p4_leaveschedule.setVisible(false);
        p4_empleave.setVisible(false);
        p4_leavereport.setVisible(false);
    
        p4.setVisible(true);
       
    }//GEN-LAST:event_btnGoBack5ActionPerformed

    private void btnGoBack5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGoBack5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoBack5KeyPressed

    private void btnaddleaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddleaveActionPerformed
        // TODO add your handling code here:

        String leave= null;
        if(rcasual.isSelected())
        {
            leave=rcasual.getText();
        }
        else if(rannual.isSelected())
        {
            leave=rannual.getText();

        }
        else if(rmedical.isSelected())
        {
            leave=rmedical.getText();

        }

        if(txtempno5.getText().equals("              Enter Employee ID to Search"))
        {
            txtempno5.setBackground(new Color(255,0,51));
            JOptionPane.showMessageDialog(this, "The EMP NO field is empty !!");
        }

        else  if(txtname.getText().isEmpty())
        {
            txtname.setBackground(new Color(255,0,51));
            JOptionPane.showMessageDialog(this, "The Name field is empty !!");
        }

        else if(txtNIC1.getText().isEmpty())
        {
            txtNIC1.setBackground(new Color(255,0,51));
            JOptionPane.showMessageDialog(this, "The NIC NO field is empty !!");
        }

        else if(txtdepartment4.getText().isEmpty())
        {
            txtdepartment4.setBackground(new Color(255,0,51));
            JOptionPane.showMessageDialog(this, "The Department field is empty !!");
        }

        else if(txtdesignation4.getText().isEmpty())
        {
            txtdesignation4.setBackground(new Color(255,0,51));
            JOptionPane.showMessageDialog(this, "The Designation field is empty !!");
        }
        else if(txtdays.getText().isEmpty())
        {
            txtdays.setBackground(new Color(255,0,51));
            JOptionPane.showMessageDialog(this, "The Leave days field is empty !!");
        }

        else if ( leave==null)
        {
            rcasual.setForeground(new java.awt.Color(255,0,51));
            rannual.setForeground(new java.awt.Color(255,0,51));
            rmedical.setForeground(new java.awt.Color(255,0,51));
            JOptionPane.showMessageDialog(this,"Please Select the Leave Type !!");
        }

        int casual1 = 0;
        int annual1 = 0;
        int medical1 = 0;

        String emp = txtempno5.getText();

        try { String le ="SELECT Casual_Leaves,Annual_Leaves,Medical_Leaves FROM `leaveinformation` WHERE EmpNo=? ";

            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/sr_bio_foods", "root", "");
            pst=(PreparedStatement) con.prepareStatement(le);

            pst.setString(1, emp);
            rs= (ResultSet) pst.executeQuery();

            if(rs.next())

            {   casual1 = rs.getInt("Casual_Leaves");
                annual1 = rs.getInt("Annual_Leaves");
                medical1 = rs.getInt("Medical_Leaves");
            } 
            }
catch (SQLException ex) {
                Logger.getLogger(Leave.class.getName()).log(Level.SEVERE, null, ex);
            }

         
        

        int bleave = 0;

        int days = Integer.parseInt (txtdays.getText());

        if(rcasual.isSelected() ==true)
        {
            bleave = casual1 - days;
            if(bleave < 0)
            {
                JOptionPane.showMessageDialog(this,"You have a Casual Leave" + casual1 );
            } else
            {
                try {
                    pst = con.prepareStatement("update leaveinformation set Casual_Leaves = ? where EmpNo= ? ");
                    pst.setInt(1, bleave);
                    pst.setString(2, emp);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this,"Your Casual Leave Updated!!!");

                } catch (SQLException ex) {
                    Logger.getLogger(Leave.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        }
        else if((rannual.isSelected() ==true))
        {
            bleave = annual1 - days;
            if(bleave < 0)
            {
                JOptionPane.showMessageDialog(this,"You have a Annual Leave" + annual1 );
            } else
            {
                try {
                    pst1 = con.prepareStatement("update leaveinformation set Annual_Leaves = ? where EmpNo= ? ");
                    pst1.setInt(1, bleave);
                    pst1.setString(2, emp);
                    pst1.executeUpdate();
                    JOptionPane.showMessageDialog(this,"Your Annual Leave Updated!!!");

                } catch (SQLException ex) {
                    Logger.getLogger(Leave.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
        else if((rmedical.isSelected() ==true))
        {
            bleave = medical1 - days;
            if(bleave < 0)
            {
                JOptionPane.showMessageDialog(this,"You have a Medical Leave" + medical1 );
            } else
            {
                try {
                    pst2 = con.prepareStatement("update leaveinformation set Medical_Leaves = ? where EmpNo= ? ");
                    pst2.setInt(1, bleave);
                    pst2.setString(2, emp);
                    pst2.executeUpdate();
                    JOptionPane.showMessageDialog(this,"Your Medical Leave Updated!!!");

                } catch (SQLException ex) {
                    Logger.getLogger(Leave.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Something Wrong!!!");

        }

    }//GEN-LAST:event_btnaddleaveActionPerformed

    private void btnreset3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreset3ActionPerformed
        // TODO add your handling code here:
        txtempno5.setText("              Enter Employee ID to Search");
        txtname.setText(null);
        txtNIC1.setText(null);
        txtdepartment4.setText(null);
        txtdesignation4.setText(null);

        lblimageleave.setIcon(null);
        txtdays.setText(null);
        rcasual.setSelected(false);
        rannual.setSelected(false);
        rmedical.setSelected(false);

    }//GEN-LAST:event_btnreset3ActionPerformed

    private void txtNIC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNIC1ActionPerformed

    private void txtNIC1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNIC1KeyPressed
        // TODO add your handling code here:
        txtNIC1.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_txtNIC1KeyPressed

    private void txtdaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdaysActionPerformed

    private void txtdaysKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdaysKeyPressed
        // TODO add your handling code here:
        txtdays.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_txtdaysKeyPressed

    private void txtadditionaldaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtadditionaldaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtadditionaldaysActionPerformed

    private void txtyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtyearActionPerformed
        // TODO add your handling code here:
        txtname.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_txtyearActionPerformed

    private void txtyearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtyearKeyPressed
        // TODO add your handling code here:
        txtyear .setBackground(new Color(255,255,255));
    }//GEN-LAST:event_txtyearKeyPressed

    private void btnreset4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreset4ActionPerformed
        // TODO add your handling code here:
        int opt = JOptionPane.showConfirmDialog(null, "Are you sure to Delete !!", "Delete", JOptionPane.YES_NO_OPTION);
        if (opt == 0) {

            try {
                String query = "DELETE  FROM leaveinformation ";
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/sr_bio_foods", "root", "");
                pst = con.prepareStatement(query);

                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "Old Schedule Delete Successfully ");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }

    }//GEN-LAST:event_btnreset4ActionPerformed

    private void btnGoBack6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGoBack6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoBack6MouseClicked

    private void btnGoBack6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBack6ActionPerformed
        // TODO add your handling code here:
      
        p4_leaveschedule.setVisible(false);
        p4_empleave.setVisible(false);
        p4_leavereport.setVisible(false);
   
        p4.setVisible(true);
      
    }//GEN-LAST:event_btnGoBack6ActionPerformed

    private void btnGoBack6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGoBack6KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoBack6KeyPressed

    private void btnaddscheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddscheduleActionPerformed
        // TODO add your handling code here

        if(jscasualleave.getText().isEmpty())
        {
            jscasualleave.setBackground(new Color(255,0,51));
            JOptionPane.showMessageDialog(this, "The Casual Leave field is empty !!");
        }

        else  if(jsannualleave.getText().isEmpty())
        {
            jsannualleave.setBackground(new Color(255,0,51));
            JOptionPane.showMessageDialog(this, "The Annual Leave field is empty !!");
        }

        else if(jsmedicalleave.getText().isEmpty())
        {
            jsmedicalleave.setBackground(new Color(255,0,51));
            JOptionPane.showMessageDialog(this, "The Medical Leave field is empty !!");
        }
        else if(txtyear.getText().isEmpty())
        {
            txtyear.setBackground(new Color(255,0,51));
            JOptionPane.showMessageDialog(this, "The  Year  field is empty !!");
        }

        String casual = jscasualleave.getText();
        String annual = jsannualleave.getText();
        String medical = jsmedicalleave.getText();
        String year = txtyear.getText();

        String emp,NIC;

        try  {

            String empk ="SELECT EmpNo,NIC_No from employee ";
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/sr_bio_foods", "root", "");
            pst=(PreparedStatement) con.prepareStatement(empk);
            rs= (ResultSet) pst.executeQuery();

            while (rs.next())  {
                emp=rs.getString("EmpNo");
                NIC=rs.getString("NIC_No");

                String leaveinformation ="INSERT INTO leaveinformation(EmpNo, NIC_No, Casual_Leaves, Annual_Leaves, Medical_Leaves, Year)  VALUES (?,?,?,?,?,?)";
                con = DriverManager.getConnection("jdbc:mysql://localhost/sr_bio_foods", "root", "");
                pst=con.prepareStatement(leaveinformation);

                pst.setString(1, emp);
                pst.setString(2, NIC);
                pst.setString(3, casual );
                pst.setString(4, annual);
                pst.setString(5, medical );
                pst.setString(6, year);
                pst.executeUpdate();

            }

            int opt =JOptionPane.showConfirmDialog(null,"Are you sure to add this Schedule!!","Add Schedule",JOptionPane.YES_NO_OPTION);
            if (opt==0)

            JOptionPane.showMessageDialog(this, "Inserted Successfully ");

        } catch (SQLException ex) {
            Logger.getLogger(Leave.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnaddscheduleActionPerformed

    private void jscasualleaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jscasualleaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jscasualleaveActionPerformed

    private void jscasualleaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jscasualleaveKeyPressed
        // TODO add your handling code here:
        jscasualleave.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jscasualleaveKeyPressed

    private void jsmedicalleaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsmedicalleaveActionPerformed
        // TODO add your handling code here:
        txtname.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jsmedicalleaveActionPerformed

    private void jsmedicalleaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsmedicalleaveKeyPressed
        // TODO add your handling code here
        jsmedicalleave.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jsmedicalleaveKeyPressed

    private void jsannualleaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsannualleaveMouseClicked
        // TODO add your handling code here:
        jsannualleave.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jsannualleaveMouseClicked

    private void jsannualleaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsannualleaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsannualleaveActionPerformed

    private void btnGoBack7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGoBack7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoBack7MouseClicked

    private void btnGoBack7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBack7ActionPerformed
        // TODO add your handling code here:
  
        p4_leaveschedule.setVisible(false);
        p4_empleave.setVisible(false);
        p4_leavereport.setVisible(false);
   
        p4.setVisible(true);
     
    }//GEN-LAST:event_btnGoBack7ActionPerformed

    private void btnGoBack7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGoBack7KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoBack7KeyPressed

    private void btnaddschedule1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddschedule1ActionPerformed
        // TODO add your handling code here:

        try {
            boolean print = EMPleavereport.print();
            if (!print) {
                JOptionPane.showMessageDialog(null, "Unable To Print !!..");
            }
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnaddschedule1ActionPerformed

    private void addionaGetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addionaGetbtnActionPerformed
      try {
                    pst = con.prepareStatement("update leaveinformation set Additional_Leaves = ? where EmpNo= ? ");
                    pst.setString(1, txtadditionaldays.getText());
                    pst.setString(2, txtempno5.getText());
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this,"Your Additional Leaves Add!!!");

                } catch (SQLException ex) {
                    Logger.getLogger(Leave.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_addionaGetbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable EMPleavereport;
    private javax.swing.JButton addionaGetbtn;
    private javax.swing.JButton btnGoBack5;
    private javax.swing.JButton btnGoBack6;
    private javax.swing.JButton btnGoBack7;
    private javax.swing.JButton btnaddleave;
    private javax.swing.JButton btnaddschedule;
    private javax.swing.JButton btnaddschedule1;
    private javax.swing.JPanel btnemployeeleave;
    private javax.swing.JButton btnreset3;
    private javax.swing.JButton btnreset4;
    private javax.swing.JPanel deleteEmployee1;
    private javax.swing.JPanel deleteEmployee2;
    private javax.swing.JPanel header5;
    private javax.swing.JPanel header6;
    private javax.swing.JPanel header7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jsannualleave;
    private javax.swing.JTextField jscasualleave;
    private javax.swing.JTextField jsmedicalleave;
    private javax.swing.JLabel lblDepartment4;
    private javax.swing.JLabel lblNIC1;
    private javax.swing.JLabel lbladditionalleave;
    private javax.swing.JLabel lblannualleave;
    private javax.swing.JLabel lblcasualleave;
    private javax.swing.JLabel lbldays;
    private javax.swing.JLabel lbldesignation4;
    private javax.swing.JLabel lblemono4;
    private javax.swing.JLabel lblimageleave;
    private javax.swing.JLabel lblmedicalleave;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblyear;
    private javax.swing.JPanel p4;
    private javax.swing.JPanel p4_empleave;
    private javax.swing.JPanel p4_leavereport;
    private javax.swing.JPanel p4_leaveschedule;
    private javax.swing.JRadioButton rannual;
    private javax.swing.JRadioButton rcasual;
    private javax.swing.JRadioButton rmedical;
    private javax.swing.JTextField txtNIC1;
    private javax.swing.JTextField txtadditionaldays;
    private javax.swing.JTextField txtdays;
    private javax.swing.JTextField txtdepartment4;
    private javax.swing.JTextField txtdesignation4;
    private javax.swing.JTextField txtempno5;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtyear;
    // End of variables declaration//GEN-END:variables
}
