/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.management.srb.inventory;

import com.management.srb.util.DBConnection;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Avishka
 */
public class dashboad extends javax.swing.JPanel {

    /**
     * Creates new form dashboard
     */
    public dashboad() {
        initComponents();
         showPieChart();
        showBarChart();
        outOfStock();
    }
 private void showPieChart() {
        //create dataset
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        try {
            Connection connection = DBConnection.getConnection();
            String sql = "SELECT productName,stock FROM product GROUP BY productID";

            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                pieDataset.setValue(rs.getString("productName"), new Double(rs.getDouble("stock")));
            }
        } catch (Exception e) {

        }

        //create chart
        JFreeChart piechart = ChartFactory.createPieChart("Current Stock", pieDataset, true, true, true);//explain

        PiePlot piePlot = (PiePlot) piechart.getPlot();

        piePlot.setBackgroundPaint(Color.white);
        piePlot.setLabelFont(new Font("SansSerif", Font.PLAIN, 12));

        //create chartPanel to display chart(graph)
        ChartPanel pieChartPanel = new ChartPanel(piechart);
        panelPieChart.removeAll();
        panelPieChart.add(pieChartPanel, BorderLayout.CENTER);
        panelPieChart.validate();
    }

    private void showBarChart() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        try {
            Connection connection = DBConnection.getConnection();
            String sql = "SELECT stock,productName,productID FROM product GROUP BY productID";

            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                dataset.setValue(rs.getDouble("stock"), "Stock", rs.getString("productName"));
            }
        } catch (Exception e) {

        }
        JFreeChart chart = ChartFactory.createBarChart("Current Quantities", "Product", "quantity",
                dataset, PlotOrientation.VERTICAL, false, true, false);

        CategoryPlot categoryPlot = chart.getCategoryPlot();
        //categoryPlot.setRangeGridlinePaint(Color.BLUE);
        categoryPlot.setBackgroundPaint(Color.WHITE);
        BarRenderer renderer = (BarRenderer) categoryPlot.getRenderer();
        Color clr3 = new Color(50, 200, 50);
        renderer.setSeriesPaint(0, clr3);

        ChartPanel barpChartPanel = new ChartPanel(chart);
        panelBarChart.removeAll();
        panelBarChart.add(barpChartPanel, BorderLayout.CENTER);
        panelBarChart.validate();
    }

    private void outOfStock() {
        try {
            Connection connection = DBConnection.getConnection();
            String sql = "SELECT COUNT(*) FROM product WHERE stock = minimumStock OR stock < minimumStock";

            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                this.lblOutOfStock.setText(String.valueOf(rs.getInt(1)));
            }
        } catch (Exception e) {

        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPieChart = new javax.swing.JPanel();
        panelBarChart = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblOutOfStock = new javax.swing.JLabel();

        setBackground(new java.awt.Color(180, 170, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPieChart.setBackground(new java.awt.Color(204, 204, 204));
        panelPieChart.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(102, 102, 102)));
        panelPieChart.setPreferredSize(new java.awt.Dimension(400, 250));
        panelPieChart.setLayout(new java.awt.BorderLayout());
        add(panelPieChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 420, 300));

        panelBarChart.setBackground(new java.awt.Color(204, 204, 204));
        panelBarChart.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(102, 102, 102)));
        panelBarChart.setPreferredSize(new java.awt.Dimension(400, 250));
        panelBarChart.setLayout(new java.awt.BorderLayout());
        add(panelBarChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 780, 240));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Out of Stock :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 170, 50));

        lblOutOfStock.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblOutOfStock.setForeground(new java.awt.Color(255, 0, 51));
        lblOutOfStock.setText("jLabel2");
        add(lblOutOfStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblOutOfStock;
    private javax.swing.JPanel panelBarChart;
    private javax.swing.JPanel panelPieChart;
    // End of variables declaration//GEN-END:variables
}
