/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.management.srb.maindashboad;

import com.management.srb.employee1.EmpMainForm;
import com.management.srb.util.Password;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



/**
 *
 * @author Avishka
 */
public class adminlogin extends javax.swing.JFrame {
     Connection con = null;
PreparedStatement pst=null;
ResultSet rs = null;
//encryption
     String saltValue = null;
 String secureValue= null;

    /**
     * Creates new form login
     */
    public adminlogin() {
        initComponents();
        setBackground (new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_user = new javax.swing.JTextField();
        login_password = new javax.swing.JPasswordField();
        ps_show = new javax.swing.JLabel();
        ps_hide = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login_user.setBackground(new java.awt.Color(53, 0, 58));
        login_user.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        login_user.setForeground(new java.awt.Color(255, 255, 255));
        login_user.setToolTipText("Enter User Name");
        login_user.setBorder(null);
        login_user.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        login_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                login_userKeyPressed(evt);
            }
        });
        getContentPane().add(login_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 210, 20));

        login_password.setBackground(new java.awt.Color(53, 0, 58));
        login_password.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        login_password.setForeground(new java.awt.Color(255, 255, 255));
        login_password.setToolTipText("Enter Password");
        login_password.setBorder(null);
        login_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                login_passwordKeyPressed(evt);
            }
        });
        getContentPane().add(login_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 363, 210, 20));

        ps_show.setToolTipText("Password show and hide");
        ps_show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ps_show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ps_showMouseClicked(evt);
            }
        });
        getContentPane().add(ps_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 357, 20, 20));

        ps_hide.setToolTipText("Password show and hide");
        ps_hide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ps_hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ps_hideMouseClicked(evt);
            }
        });
        getContentPane().add(ps_hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 357, 20, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/maindashboad/cut.png"))); // NOI18N
        jLabel3.setToolTipText("Cut");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 19, 20));

        login.setBackground(new java.awt.Color(53, 0, 58));
        login.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Login");
        login.setToolTipText("Login");
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginKeyPressed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 130, 50));

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 0, 35)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TO  ADMIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 56, 150, 30));

        jLabel4.setBackground(new java.awt.Color(53, 0, 58));
        jLabel4.setFont(new java.awt.Font("Arial Narrow", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 70, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/maindashboad/sr boa food login design 1024 768 ps hide.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 393, 678));

        setSize(new java.awt.Dimension(390, 640));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
         new login_chooser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void ps_showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ps_showMouseClicked
        ps_hide.setVisible(true);
        ps_hide.setEnabled(true);
        login_password.setEchoChar((char)0);
        ImageIcon A= new ImageIcon (getClass().getResource("sr boa food login design 1024 768 ps show.png"));
        jLabel2.setIcon(A);
        ps_show.setVisible(false);
        ps_show.setEnabled(false);
        
    }//GEN-LAST:event_ps_showMouseClicked

    private void ps_hideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ps_hideMouseClicked
        ps_show.setVisible(true);
        ps_show.setEnabled(true);
        login_password.setEchoChar((char)42);
        ImageIcon A= new ImageIcon (getClass().getResource("sr boa food login design 1024 768 ps hide.png"));
        jLabel2.setIcon(A);
        ps_hide.setVisible(false);
        ps_hide.setEnabled(false);
    }//GEN-LAST:event_ps_hideMouseClicked

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
              this.login();
    }//GEN-LAST:event_loginActionPerformed

    private void loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
        this.login();
    }
    }//GEN-LAST:event_loginKeyPressed

    private void login_userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_userKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
        this.login();
    }
    }//GEN-LAST:event_login_userKeyPressed

    private void login_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_passwordKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
        this.login();
    }
    }//GEN-LAST:event_login_passwordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminlogin().setVisible(true);
            }
        });
    }
private void decrypt(){
        // User provided password to validate
        String providedPassword = this.login_password.getText();
        
        try{
            String query = "SELECT Id,User_Name,Password,Designation,DP,salt,secure FROM login WHERE Id=? and User_Type='Admin'";
            con = DriverManager.getConnection("jdbc:mysql://localhost/sr_bio_foods", "root", "");
            pst=con.prepareStatement(query);
             pst.setString(1,login_user.getText());
            rs=pst.executeQuery();
            while(rs.next()){
                    this.saltValue=(rs.getString("salt"));
                   this.secureValue=(rs.getString("secure"));  
            }
            if(this.saltValue.isEmpty()||this.secureValue.isEmpty()){
            JOptionPane.showMessageDialog(this, "You are not assigned, Please contact admin to Reassign");
            
        }
        }catch(Exception e){
            
        }
                
        // Encrypted and Base64 encoded password read from database
        String securePassword = this.secureValue;
        
        // Salt value stored in database 
        String salt = this.saltValue;
        
        boolean passwordMatch = Password.verifyUserPassword(providedPassword, securePassword, salt);
        
        if(passwordMatch) 
        {
            System.out.println("Provided user password " + providedPassword + " is correct.");
        } else {
            System.out.println("Provided password is incorrect");
        }
    }
    private void login(){
        decrypt();
         try{
            String query = "SELECT Id,User_Name,Password,Designation,DP,salt,secure FROM login WHERE Id=? and password=? and User_Type='Admin'";
            con = DriverManager.getConnection("jdbc:mysql://localhost/sr_bio_foods", "root", "");
            pst=con.prepareStatement(query);

            pst.setString(1,login_user.getText());
            pst.setString(2, login_password.getText());
            rs=pst.executeQuery();
            if(rs.next()){
            //    JOptionPane.showMessageDialog(this, "UserID and Password matched and you are logined ");
                   
                    String admin = login_user.getText().toString();
                   String name=(rs.getString("User_Name"));
                   String designation=(rs.getString("Designation"));

                  
              
                
                    adminmenu u = new adminmenu();
                    u.setVisible(true);
                    this.setVisible(false);
                    
                    u.adminid(admin);
                    u.adminname(name);
                    u.admindesignation(designation);
                    
                     
                }
            else
            {
                JOptionPane.showMessageDialog(this, "UserID and password do not matched Or you are not Admin");
                
                }
        } catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
            
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField login_password;
    private javax.swing.JTextField login_user;
    private javax.swing.JLabel ps_hide;
    private javax.swing.JLabel ps_show;
    // End of variables declaration//GEN-END:variables
}
