/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.management.srb.maindashboad;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.Timer;

/**
 *
 * @author Avishka
 */
public final class adminmenu extends javax.swing.JFrame {

    int mouseX;
    int mouseY;
    JpanelLoader jpload = new JpanelLoader();

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form adminmenu
     */
    public adminmenu() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));

        dashbord.setSelected(true);
        dashbord.setBackground(new Color(0, 204, 204));

        sr_main_home home = new sr_main_home();
        jpload.jPanelLoader(home_panel, home);

        dplbl();

        showDate();
        showTime();

    }

    void adminid(String admin) {
        adminlb.setText(admin);
    }

    void adminname(String name) {
        namelbl.setText(name);
    }

    void admindesignation(String designation) {
        designationlbl.setText(designation);
    }

    void dplbl() {
        try {
            String sql = "SELECT DP FROM login where Id='" + adminlb.getText() + "' ";
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/sr_bio_foods", "root", "");
            pst = (PreparedStatement) con.prepareStatement(sql);
            rs = (ResultSet) pst.executeQuery();
            if (rs.next()) {
                byte[] img = rs.getBytes("DP");
                ImageIcon proimage = new ImageIcon(img);
                Image im = proimage.getImage();
                Image myImg = im.getScaledInstance(90, 90, WIDTH);
                ImageIcon newImage = new ImageIcon(myImg);
                dp.setIcon(newImage);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }

    }

    void showDate() {
        Date d = new Date();
        SimpleDateFormat s;
        s = new SimpleDateFormat("yyyy-MM-dd");
        datelable.setText(s.format(d));

    }

    void showTime() {
        new Timer(0, (ActionEvent e) -> {
            Date d = new Date();
            SimpleDateFormat s = new SimpleDateFormat("H:mm:ss");
            timelable.setText(s.format(d));
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        dp = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        adminlb = new javax.swing.JLabel();
        namelbl = new javax.swing.JLabel();
        designationlbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        timelable = new javax.swing.JLabel();
        datelable = new javax.swing.JLabel();
        userlogout = new javax.swing.JButton();
        usercontroller = new javax.swing.JToggleButton();
        dashbord = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        home_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        drag = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/icons/cancel1.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 25, -1, 30));

        dp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(dp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 90, 90));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/icons/home(1).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 372, 40, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/icons/sign_out(1).png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 680, 40, 32));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/icons/access_control_write.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 470, 30, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/icons/minimize.png"))); // NOI18N
        jLabel8.setToolTipText("Minimize");
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 30, 20, 20));

        adminlb.setBackground(new java.awt.Color(255, 255, 255));
        adminlb.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        adminlb.setForeground(new java.awt.Color(255, 255, 255));
        adminlb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminlb.setText("admin");
        adminlb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                adminlbFocusGained(evt);
            }
        });
        getContentPane().add(adminlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 130, 20));

        namelbl.setBackground(new java.awt.Color(255, 255, 255));
        namelbl.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        namelbl.setForeground(new java.awt.Color(255, 255, 255));
        namelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namelbl.setText("name");
        getContentPane().add(namelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 130, 20));

        designationlbl.setBackground(new java.awt.Color(255, 255, 255));
        designationlbl.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        designationlbl.setForeground(new java.awt.Color(255, 255, 255));
        designationlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        designationlbl.setText("designation");
        getContentPane().add(designationlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 130, 20));

        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 255), 2, true));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 14, 170, 190));

        timelable.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        timelable.setForeground(new java.awt.Color(255, 255, 255));
        timelable.setText("Time :");
        getContentPane().add(timelable, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 120, 30));

        datelable.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        datelable.setForeground(new java.awt.Color(255, 255, 255));
        datelable.setText("Date :");
        getContentPane().add(datelable, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 150, 30));

        userlogout.setBackground(new java.awt.Color(255, 153, 153));
        userlogout.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        userlogout.setText("Log Out");
        userlogout.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        userlogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(userlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, 180, 50));

        usercontroller.setBackground(new java.awt.Color(102, 255, 255));
        usercontroller.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        usercontroller.setText("Controll Panel");
        usercontroller.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        usercontroller.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usercontroller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usercontrollerActionPerformed(evt);
            }
        });
        getContentPane().add(usercontroller, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 180, 60));

        dashbord.setBackground(new java.awt.Color(102, 255, 255));
        dashbord.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        dashbord.setText("Dashboard");
        dashbord.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(51, 51, 51)));
        dashbord.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashbord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashbordMouseClicked(evt);
            }
        });
        dashbord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashbordActionPerformed(evt);
            }
        });
        dashbord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dashbordKeyPressed(evt);
            }
        });
        getContentPane().add(dashbord, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 180, 60));
        dashbord.getAccessibleContext().setAccessibleDescription("");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SRBF Management");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 350, 40));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/icons/sr boa food Main form design side panel1024 768.png"))); // NOI18N
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 210, 770));

        home_panel.setBackground(new java.awt.Color(215, 215, 215));
        home_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(home_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 70, 820, 700));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/icons/sr boa food Main form design 2 1024 768.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));

        drag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragMouseDragged(evt);
            }
        });
        drag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragMousePressed(evt);
            }
        });
        getContentPane().add(drag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 770));

        setSize(new java.awt.Dimension(1024, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        double i;
        for (i = 0.0; i <= 1.0; i = i + 0.1) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(50);

            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void dashbordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashbordMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dashbordMouseClicked

    private void dashbordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashbordActionPerformed
        sr_main_home home = new sr_main_home();
        jpload.jPanelLoader(home_panel, home);
        if (dashbord.isSelected()) {

            dashbord.setBackground(new Color(0, 204, 204));
            usercontroller.setSelected(false);
            usercontroller.setBackground(new Color(102, 255, 255));

        }
        if (home_panel.equals(home));
        {
            dashbord.setSelected(true);
            dashbord.setBackground(new Color(0, 204, 204));
        }

    }//GEN-LAST:event_dashbordActionPerformed

    private void dashbordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dashbordKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dashbordKeyPressed

    private void usercontrollerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usercontrollerActionPerformed
        String adid = null;
        String adpass = null;
        String opid = null;
        String oppass = null;
        try {
            String sql = "SELECT Id,Password FROM login where Designation='owner' ";
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/sr_bio_foods", "root", "");
            pst = (PreparedStatement) con.prepareStatement(sql);
            rs = (ResultSet) pst.executeQuery();
            if (rs.next()) {
                adid = (rs.getString("Id"));
                adpass = (rs.getString("Password"));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
        try {
            String sql = "SELECT Id,Password FROM login where Designation='Manager' ";
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/sr_bio_foods", "root", "");
            pst = (PreparedStatement) con.prepareStatement(sql);
            rs = (ResultSet) pst.executeQuery();
            if (rs.next()) {
                opid = (rs.getString("Id"));
                oppass = (rs.getString("Password"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }

        String id = JOptionPane.showInputDialog("Please Enter Id").toLowerCase();

        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Id");
        } else if (id != null) {
            JPasswordField pwd = new JPasswordField(10);
            int action = JOptionPane.showConfirmDialog(null, pwd, "Enter Password", JOptionPane.OK_CANCEL_OPTION);
            requestFocus();
            if (action < 0) {
                JOptionPane.showMessageDialog(null, "Cancel, X or escape key selected");
            }
            // else JOptionPane.showMessageDialog(null,"Your password is "+new String(pwd.getPassword()));

            String pass = new String(pwd.getPassword());
//JOptionPane.showInputDialog("Please Enter Password");
            if ((id.equals(adid) && pass.equals(adpass)) || (id.equals(opid) && pass.equals(oppass))) {

                Settings sett = new Settings();
                jpload.jPanelLoader(home_panel, sett);

                if (usercontroller.isSelected()) {
                    usercontroller.setBackground(new Color(0, 204, 204));
                    dashbord.setSelected(false);
                    dashbord.setBackground(new Color(102, 255, 255));

                }
                if (home_panel.equals(sett));
                {
                    usercontroller.setSelected(true);
                    usercontroller.setBackground(new Color(0, 204, 204));
                }
            } else {
                JOptionPane.showMessageDialog(this, "Can't access. You are not owner or operator");
            }

        }
    }//GEN-LAST:event_usercontrollerActionPerformed

    private void userlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userlogoutActionPerformed
        if (userlogout.isSelected()) {
            userlogout.setBackground(new Color(160, 0, 51));

        }

        int opt = JOptionPane.showConfirmDialog(null, "Are you sure to Log Out !!", "Log Out", JOptionPane.YES_NO_OPTION);
        if (opt == 0) {
            this.dispose();
            new login_chooser().setVisible(true);
        }
    }//GEN-LAST:event_userlogoutActionPerformed

    private void adminlbFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adminlbFocusGained
        try {
            String sql = "SELECT DP FROM login where Id='" + adminlb.getText() + "' ";
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/sr_bio_foods", "root", "");
            pst = (PreparedStatement) con.prepareStatement(sql);
            rs = (ResultSet) pst.executeQuery();
            if (rs.next()) {
                byte[] img = rs.getBytes("DP");
                ImageIcon proimage = new ImageIcon(img);
                Image im = proimage.getImage();
                Image myImg = im.getScaledInstance(dp.getWidth(), dp.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myImg);
                dp.setIcon(newImage);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_adminlbFocusGained


    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.setExtendedState(adminmenu.ICONIFIED);

    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        int opt = JOptionPane.showConfirmDialog(null, "Are you sure to Log Out !!", "Log Out", JOptionPane.YES_NO_OPTION);
        if (opt == 0) {
            this.dispose();
            new login_chooser().setVisible(true);
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void adminlbAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_adminlbAncestorAdded
        dplbl();
    }//GEN-LAST:event_adminlbAncestorAdded

    private void dragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMouseDragged
        int X = evt.getXOnScreen();
        int Y = evt.getYOnScreen();
        this.setLocation(X - mouseX, Y - mouseY);
    }//GEN-LAST:event_dragMouseDragged

    private void dragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_dragMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminlb;
    private javax.swing.JToggleButton dashbord;
    private javax.swing.JLabel datelable;
    private javax.swing.JLabel designationlbl;
    private javax.swing.JLabel dp;
    private javax.swing.JLabel drag;
    private javax.swing.JPanel home_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel namelbl;
    private javax.swing.JLabel timelable;
    private javax.swing.JToggleButton usercontroller;
    private javax.swing.JButton userlogout;
    // End of variables declaration//GEN-END:variables

    void admindp(byte[] img) {

    }
}
