/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.management.srb.maindashboad;

import java.awt.Color;
import com.management.srb.employee1.EmpMainForm;
import com.management.srb.inventory.Invenmain;
import com.management.srb.invoice1.Invoicemain;

/**
 *
 * @author Avishka
 */
public class sr_main_home extends javax.swing.JPanel {
  JpanelLoader jpload = new JpanelLoader();
    /**
     * Creates new form srmain
     */
    public sr_main_home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home_panel = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        invoicebtn = new javax.swing.JButton();
        employeebtn = new javax.swing.JButton();
        inventorybtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        notify = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        home_panel.setBackground(new java.awt.Color(180, 170, 255));
        home_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(51, 204, 0));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("Employee");
        home_panel.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, -1, 30));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(51, 204, 0));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Inventory");
        home_panel.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, 30));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(51, 204, 0));
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Invoice");
        home_panel.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 90, 30));

        invoicebtn.setBackground(new java.awt.Color(204, 255, 255));
        invoicebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/icons/invoice (1).png"))); // NOI18N
        invoicebtn.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 51, 51)));
        invoicebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        invoicebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoicebtnActionPerformed(evt);
            }
        });
        home_panel.add(invoicebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 210, 170));

        employeebtn.setBackground(new java.awt.Color(204, 255, 255));
        employeebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/icons/construction_worker.png"))); // NOI18N
        employeebtn.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 51, 51)));
        employeebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employeebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeebtnActionPerformed(evt);
            }
        });
        home_panel.add(employeebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 210, 170));

        inventorybtn.setBackground(new java.awt.Color(204, 255, 255));
        inventorybtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/management/srb/icons/inventory (5).png"))); // NOI18N
        inventorybtn.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 51, 51)));
        inventorybtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inventorybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventorybtnActionPerformed(evt);
            }
        });
        home_panel.add(inventorybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 210, 170));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel4.setText("WELCOME TO SR BIO FOODS");
        home_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 500, 60));
        home_panel.add(notify, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 590, 240, 90));

        jLabel8.setBackground(new java.awt.Color(180, 170, 255));
        home_panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 825, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inventorybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventorybtnActionPerformed
      if(inventorybtn.isSelected())
{
 inventorybtn.setBackground(new Color(255,153,102));

}
      new Invenmain().setVisible(true);
    }//GEN-LAST:event_inventorybtnActionPerformed

    private void invoicebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoicebtnActionPerformed
        if(invoicebtn.isSelected())
{
 invoicebtn.setBackground(new Color(255,153,102));

}
           new Invoicemain().setVisible(true);
    }//GEN-LAST:event_invoicebtnActionPerformed

    private void employeebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeebtnActionPerformed
        if(employeebtn.isSelected())
{
 employeebtn.setBackground(new Color(255,153,102));

}
          new EmpMainForm().setVisible(true);
         
        
    }//GEN-LAST:event_employeebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton employeebtn;
    private javax.swing.JPanel home_panel;
    private javax.swing.JButton inventorybtn;
    private javax.swing.JButton invoicebtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel notify;
    // End of variables declaration//GEN-END:variables
}
